# Generated by Django 5.0 on 2025-07-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnableErrorLogging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_error_logging', models.BooleanField(default=False, verbose_name='логировать ошибки')),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.CharField(max_length=15, verbose_name='ip с которого был запрос')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='время')),
                ('status', models.SmallIntegerField(null=True, verbose_name='статус')),
                ('message', models.TextField(max_length=10000, verbose_name='сообщение об ошибке')),
                ('path', models.CharField(max_length=200, verbose_name='страница')),
            ],
        ),
        migrations.CreateModel(
            name='TestUserSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_count', models.PositiveSmallIntegerField(verbose_name='Количество пользователей')),
            ],
        ),
    ]
