# Generated by Django 5.0 on 2024-09-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_tests", "0002_error"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnableErrorLogging",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("enable_error_logging", models.BooleanField(default=False, verbose_name="логировать ошибки")),
            ],
        ),
    ]
