# Generated by Django 4.2 on 2024-08-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserMessanger",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("adress", models.CharField(max_length=100, verbose_name="адресс")),
            ],
        ),
        migrations.CreateModel(
            name="UserSocialNetwork",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("adress", models.CharField(max_length=100, verbose_name="адресс")),
            ],
            options={
                "verbose_name": "пользовательская соц. сеть",
                "verbose_name_plural": "пользовательские соц. сети",
            },
        ),
    ]
