# Generated by Django 4.2 on 2024-09-01 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0001_initial"),
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSocialNetwork",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("adress", models.CharField(max_length=100, verbose_name="адресс")),
                (
                    "site",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="socials",
                        to="user.site",
                        verbose_name="сайт",
                    ),
                ),
                (
                    "social_network",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="settings.socialnetwork",
                        verbose_name="соц. сеть",
                    ),
                ),
            ],
            options={
                "verbose_name": "пользовательская соц. сеть",
                "verbose_name_plural": "пользовательские соц. сети",
            },
        ),
        migrations.CreateModel(
            name="UserMessanger",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("adress", models.CharField(max_length=100, verbose_name="адресс")),
                (
                    "messanger",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="settings.messanger",
                        verbose_name="Соц. сеть",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messanger",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
    ]
