# Generated by Django 4.2 on 2024-08-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Messanger",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "verbose_name": "Мессенджер",
                "verbose_name_plural": "Мессенджеры",
            },
        ),
        migrations.CreateModel(
            name="UserFont",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="Имя шрифта")),
                (
                    "link",
                    models.CharField(blank=True, max_length=250, null=True, verbose_name="Ссылка для подключения"),
                ),
            ],
            options={
                "verbose_name": "пользовательский шрифт",
                "verbose_name_plural": "пользовательские шрифты",
            },
        ),
        migrations.CreateModel(
            name="UserMessanger",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("adress", models.CharField(max_length=100, verbose_name="адресс")),
            ],
        ),
        migrations.CreateModel(
            name="UserSocialNetwork",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("adress", models.CharField(max_length=100, verbose_name="адресс")),
            ],
            options={
                "verbose_name": "пользовательская соц. сеть",
                "verbose_name_plural": "пользовательские соц. сети",
            },
        ),
    ]
