# Generated by Django 4.2.7 on 2024-07-03 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_socialnetwork"),
        ("domens", "0007_alter_site_online_from"),
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSocialNetwork",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("adress", models.CharField(max_length=100, verbose_name="адресс")),
                (
                    "site",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="domens.site", verbose_name="сайт"
                    ),
                ),
                (
                    "social_network",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="common.socialnetwork",
                        verbose_name="соц. сеть",
                    ),
                ),
            ],
            options={
                "verbose_name": "пользовательская соц. сеть",
                "verbose_name_plural": "пользовательские соц. сети",
            },
        ),
    ]
