# Generated by Django 4.2 on 2024-08-02 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("domens", "0001_initial"),
        ("account", "0001_initial"),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersocialnetwork",
            name="site",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="socials",
                to="domens.site",
                verbose_name="сайт",
            ),
        ),
        migrations.AddField(
            model_name="usersocialnetwork",
            name="social_network",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.socialnetwork",
                verbose_name="соц. сеть",
            ),
        ),
        migrations.AddField(
            model_name="usermessanger",
            name="messanger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="account.messanger", verbose_name="Соц. сеть"
            ),
        ),
    ]
