# Generated by Django 4.2 on 2024-08-21 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("settings", "0001_initial"),
        ("user", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersocialnetwork",
            name="site",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="socials",
                to="user.site",
                verbose_name="сайт",
            ),
        ),
        migrations.AddField(
            model_name="usersocialnetwork",
            name="social_network",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="settings.socialnetwork",
                verbose_name="соц. сеть",
            ),
        ),
        migrations.AddField(
            model_name="usermessanger",
            name="messanger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="settings.messanger", verbose_name="Соц. сеть"
            ),
        ),
        migrations.AddField(
            model_name="usermessanger",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messanger",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
