# Generated by Django 4.2 on 2024-08-02 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0002_initial"),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermessanger",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messanger",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="messanger",
            name="social_network",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.socialnetwork", verbose_name="Соц. сеть"
            ),
        ),
    ]
