# Generated by Django 4.2 on 2024-08-06 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userfont",
            options={
                "ordering": ["name"],
                "verbose_name": "пользовательский шрифт",
                "verbose_name_plural": "пользовательские шрифты",
            },
        ),
    ]
