# Generated by Django 4.2 on 2024-07-21 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_alter_blockrelationship_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0003_alter_usersocialnetwork_site"),
    ]

    operations = [
        migrations.CreateModel(
            name="Messanger",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "social_network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.socialnetwork", verbose_name="Соц. сеть"
                    ),
                ),
            ],
            options={
                "verbose_name": "Мессенджер",
                "verbose_name_plural": "Мессенджеры",
            },
        ),
        migrations.CreateModel(
            name="UserMessanger",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "messanger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.messanger", verbose_name="Соц. сеть"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messanger",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
    ]
