# Generated by Django 4.2 on 2024-07-21 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0004_messanger"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMessanger",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("adress", models.CharField(max_length=100, verbose_name="адресс")),
                (
                    "messanger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.messanger", verbose_name="Соц. сеть"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messanger",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
    ]
