# Generated by Django 4.2 on 2024-08-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="slug",
            field=models.SlugField(null=True),
        ),
    ]
