# Generated by Django 4.2 on 2024-08-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_document_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
