# Generated by Django 4.2 on 2024-08-21 18:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_alter_document_slug"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Document",
        ),
        migrations.RemoveField(
            model_name="messanger",
            name="social_network",
        ),
    ]
