# Generated by Django 4.2 on 2024-08-21 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0008_delete_document_remove_messanger_social_network"),
        ("user", "0006_alter_user_register_on_domain_site_and_more"),
        ("domens", "0013_remove_site_domain_remove_site_font_remove_site_user_and_more"),
        ("settings", "0002_domain_font_globalstyles_socialnetwork_userfont_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserFont",
        ),
        migrations.AlterField(
            model_name="usermessanger",
            name="messanger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="settings.messanger", verbose_name="Соц. сеть"
            ),
        ),
        migrations.AlterField(
            model_name="usersocialnetwork",
            name="site",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="socials",
                to="user.site",
                verbose_name="сайт",
            ),
        ),
        migrations.AlterField(
            model_name="usersocialnetwork",
            name="social_network",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="settings.socialnetwork",
                verbose_name="соц. сеть",
            ),
        ),
        migrations.DeleteModel(
            name="Messanger",
        ),
    ]
