# Generated by Django 5.0 on 2025-07-13 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=100, verbose_name='адресс')),
            ],
            options={
                'verbose_name': 'пользовательская соц. сеть',
                'verbose_name_plural': 'пользовательские соц. сети',
            },
        ),
        migrations.CreateModel(
            name='UserMessanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=100, verbose_name='адресс')),
                ('messanger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.messanger', verbose_name='Соц. сеть')),
            ],
        ),
    ]
