# Generated by Django 5.0 on 2025-07-13 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('settings', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessanger',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messanger', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='usersocialnetwork',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='socials', to='user.site', verbose_name='сайт'),
        ),
        migrations.AddField(
            model_name='usersocialnetwork',
            name='social_network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.socialnetwork', verbose_name='соц. сеть'),
        ),
    ]
