# Generated by Django 5.0 on 2024-10-30 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0004_alter_document_name_alter_document_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentFormatPattern",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tag", models.CharField(max_length=50, verbose_name="Тэг")),
                ("text", models.CharField(max_length=50, verbose_name="Текст")),
                (
                    "method",
                    models.CharField(
                        choices=[("openUserForm", "openUserForm"), ("openUpdateProductForm", "openUpdateProductForm")],
                        max_length=50,
                        verbose_name="Метод",
                    ),
                ),
                ("arg", models.CharField(blank=True, max_length=50, null=True, verbose_name="Аргумент")),
                ("document", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="materials.document")),
            ],
            options={
                "verbose_name": "",
            },
        ),
    ]
