# Generated by Django 5.0 on 2024-10-30 02:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0005_documentformatpattern"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentformatpattern",
            options={"verbose_name": "Подстановочные шаблоны", "verbose_name_plural": "Подстановочные шаблоны"},
        ),
    ]
