# Generated by Django 5.0 on 2024-10-30 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationFormatPattern",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tag", models.CharField(max_length=50, verbose_name="Тэг")),
                ("text", models.CharField(max_length=50, verbose_name="Текст")),
                (
                    "method",
                    models.CharField(
                        choices=[("openUserForm", "openUserForm"), ("openUpdateProductForm", "openUpdateProductForm")],
                        max_length=50,
                        verbose_name="Метод",
                    ),
                ),
                ("arg", models.CharField(blank=True, max_length=50, null=True, verbose_name="Аргумент")),
                (
                    "notification",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="notifications.notification"),
                ),
            ],
            options={
                "verbose_name": "Подстановочные шаблоны",
                "verbose_name_plural": "Подстановочные шаблоны",
                "abstract": False,
            },
        ),
    ]
