# Generated by Django 5.0 on 2024-10-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_notificationformatpattern"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationformatpattern",
            name="method",
            field=models.CharField(
                blank=True,
                choices=[("openUserForm", "openUserForm"), ("openUpdateProductForm", "openUpdateProductForm")],
                max_length=50,
                null=True,
                verbose_name="Метод",
            ),
        ),
    ]
