# Generated by Django 5.0 on 2025-01-02 21:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("messanger", "0002_message_text_alter_chatuser_chat"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["time"]},
        ),
    ]
