# Generated by Django 4.2 on 2024-05-10 10:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0001_initial"),
        ("blocks", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ContentBlock",
            new_name="ExampleBlock",
        ),
    ]
