# Generated by Django 4.2 on 2024-04-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cover",
            name="ancor",
            field=models.CharField(max_length=50, null=True, verbose_name="Якорь"),
        ),
        migrations.AddField(
            model_name="exampleblock",
            name="ancor",
            field=models.CharField(max_length=50, null=True, verbose_name="Якорь"),
        ),
        migrations.AddField(
            model_name="navbar",
            name="ancor",
            field=models.CharField(max_length=50, null=True, verbose_name="Якорь"),
        ),
    ]
