# Generated by Django 4.2.7 on 2024-06-04 15:14

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_alter_blockrelationship_table"),
        ("catalog", "0001_initial"),
        ("blocks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True, verbose_name="Имя")),
                ("ancor", models.CharField(blank=True, max_length=50, null=True, verbose_name="Якорь")),
                ("title", models.CharField(blank=True, max_length=100, null=True, verbose_name="Заголовок")),
                ("button_text", models.CharField(blank=True, max_length=20, null=True, verbose_name="Текст кнопки")),
                (
                    "button_ref",
                    models.CharField(blank=True, max_length=20, null=True, verbose_name="Ссылка для кнопки"),
                ),
                ("introductory_text", ckeditor.fields.RichTextField(max_length=300, verbose_name="Введение")),
                (
                    "add_exclusive",
                    models.BooleanField(
                        help_text="нужно ли добавлять карточку приватного продукта", verbose_name="Эксклюзив"
                    ),
                ),
                (
                    "block_relation",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="common.blockrelationship"
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="catalog.producttype"),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blocks.template", verbose_name="html шаблон"
                    ),
                ),
            ],
            options={
                "verbose_name": "Блок каталога",
                "verbose_name_plural": "Блоки каталога",
                "db_table": "blocks_catalogblock",
            },
        ),
        migrations.CreateModel(
            name="CatalogProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("my_order", models.PositiveIntegerField(default=0)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="products", to="blocks.catalogblock"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "ordering": ["my_order"],
                "abstract": False,
            },
        ),
    ]
