# Generated by Django 4.2 on 2024-04-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampleblock',
            name='button_ref',
            field=models.CharField(max_length=20, null=True, verbose_name='Ссылка для кнопки'),
        ),
        migrations.AddField(
            model_name='exampleblock',
            name='button_text',
            field=models.CharField(max_length=20, null=True, verbose_name='Текст кнопки'),
        ),
    ]
