# Generated by Django 4.2 on 2024-08-21 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0002_domain_font_globalstyles_socialnetwork_userfont_and_more"),
        ("catalog", "0002_alter_product_name_alter_product_status"),
        ("blocks", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="additionalcatalogblock",
            options={"verbose_name": "Мини витрина", "verbose_name_plural": "Мини витрины"},
        ),
        migrations.AlterField(
            model_name="catalogproduct",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalog_product",
                to="catalog.product",
                verbose_name="Продукт",
            ),
        ),
        migrations.AlterField(
            model_name="socialmediabutton",
            name="social_network",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="settings.socialnetwork",
                verbose_name="Соц. сеть",
            ),
        ),
    ]
