# Generated by Django 4.2 on 2024-05-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0002_rename_block_id_blockrelationship_block"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockrelationship",
            name="block",
            field=models.CharField(max_length=50),
        ),
    ]
