# Generated by Django 4.2.7 on 2024-06-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogblock",
            name="page_title",
            field=models.CharField(max_length=100, null=True, verbose_name="Заголовок страницы"),
        ),
    ]
