# Generated by Django 4.2.7 on 2024-06-05 21:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0002_catalogblock_catalogproduct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogblock",
            name="add_exclusive",
            field=models.BooleanField(
                help_text="нужно ли добавлять карточку приватного продукта", null=True, verbose_name="Эксклюзив"
            ),
        ),
        migrations.AlterField(
            model_name="catalogblock",
            name="introductory_text",
            field=ckeditor.fields.RichTextField(max_length=300, null=True, verbose_name="Введение"),
        ),
    ]
