# Generated by Django 4.2 on 2024-05-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0002_rename_contentblock_exampleblock"),
    ]

    operations = [
        migrations.AddField(
            model_name="navbar",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Заголовок"),
        ),
    ]
