# Generated by Django 4.2 on 2024-05-12 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0002_socialmediabutton_question_navmenuitem_feature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="questions", to="blocks.questionsblock"
            ),
        ),
    ]
