# Generated by Django 4.2 on 2024-04-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0002_cover_ancor_exampleblock_ancor_navbar_ancor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cover",
            name="ancor",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Якорь"),
        ),
        migrations.AlterField(
            model_name="exampleblock",
            name="ancor",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Якорь"),
        ),
        migrations.AlterField(
            model_name="navbar",
            name="ancor",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Якорь"),
        ),
    ]
