# Generated by Django 4.2.7 on 2024-06-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0003_alter_catalogblock_add_exclusive_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="url",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
