# Generated by Django 4.2 on 2024-05-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0003_alter_question_block"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentblock",
            name="image1",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/content/", verbose_name="Первое изображение"
            ),
        ),
        migrations.AlterField(
            model_name="contentblock",
            name="image2",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/content/", verbose_name="Второе изображение"
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="icon",
            field=models.ImageField(upload_to="images/features", verbose_name="Иконка"),
        ),
    ]
