# Generated by Django 4.2 on 2024-05-10 10:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0001_initial"),
        ("blocks", "0003_navbar_title"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ExampleBlock",
            new_name="ContentBlock",
        ),
    ]
