# Generated by Django 4.2 on 2024-05-07 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0003_alter_blockrelationship_block"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeaturesBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("name", models.CharField(max_length=50, unique=True, verbose_name="Имя")),
                ("ancor", models.CharField(blank=True, max_length=50, null=True, verbose_name="Якорь")),
                ("button_text", models.CharField(max_length=20, verbose_name="Текст кнопки")),
                ("button_ref", models.CharField(max_length=20, verbose_name="Ссылка для кнопки")),
                ("introductory_text", models.CharField(max_length=100, verbose_name="Вводный текст")),
                (
                    "block_relation",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="blocks.blockrelationship"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blocks.template", verbose_name="html шаблон"
                    ),
                ),
            ],
            options={
                "verbose_name": "Блок с фичами",
                "verbose_name_plural": "Блоки с фичами",
            },
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("icon", models.ImageField(upload_to="images/features", verbose_name="Иконка")),
                ("description", models.TextField(verbose_name="Пояснение")),
                (
                    "block",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="blocks.featuresblock",
                        verbose_name="Блок",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
