# Generated by Django 5.0 on 2024-09-09 20:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0003_alter_additionalcatalogproducttype_product_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="additionalcatalogproducttype",
            old_name="product",
            new_name="offer",
        ),
        migrations.RenameField(
            model_name="catalogproducttype",
            old_name="product",
            new_name="offer",
        ),
    ]
