# Generated by Django 4.2.7 on 2024-06-22 11:21

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
        ("blocks", "0003_catalogblock_page_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="catalogblock",
            name="page_title",
        ),
        migrations.CreateModel(
            name="MainPageCatalogBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True, verbose_name="Имя")),
                ("ancor", models.CharField(blank=True, max_length=50, null=True, verbose_name="Якорь")),
                ("title", models.CharField(blank=True, max_length=100, null=True, verbose_name="Заголовок")),
                ("button_text", models.CharField(blank=True, max_length=20, null=True, verbose_name="Текст кнопки")),
                (
                    "button_ref",
                    models.CharField(blank=True, max_length=20, null=True, verbose_name="Ссылка для кнопки"),
                ),
                (
                    "introductory_text",
                    ckeditor.fields.RichTextField(max_length=300, null=True, verbose_name="Введение"),
                ),
                (
                    "add_exclusive",
                    models.BooleanField(
                        help_text="нужно ли добавлять карточку приватного продукта", null=True, verbose_name="Эксклюзив"
                    ),
                ),
                ("page_title", models.CharField(max_length=100, null=True, verbose_name="Заголовок страницы")),
                (
                    "block_relation",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="common.blockrelationship"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blocks.template", verbose_name="html шаблон"
                    ),
                ),
            ],
            options={
                "verbose_name": "Блок каталога на главной",
                "verbose_name_plural": "Блоки каталога на главной",
            },
        ),
    ]
