# Generated by Django 4.2 on 2024-05-10 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0004_rename_exampleblock_contentblock"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="contentblock",
            table=None,
        ),
    ]
