# Generated by Django 4.2.7 on 2024-06-22 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_alter_product_options"),
        ("blocks", "0004_remove_catalogblock_page_title_mainpagecatalogblock"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogProductType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("my_order", models.PositiveIntegerField(default=0)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="blocks.mainpagecatalogblock",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.producttype",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "ordering": ["my_order"],
                "abstract": False,
            },
        ),
    ]
