# Generated by Django 4.2.7 on 2024-06-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0004_promocatalog"),
    ]

    operations = [
        migrations.AddField(
            model_name="promocatalog",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Заголовок"),
        ),
    ]
