# Generated by Django 5.0 on 2024-09-09 20:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0004_rename_product_additionalcatalogproducttype_offer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="additionalcatalogproducttype",
            name="offer",
        ),
        migrations.RemoveField(
            model_name="catalogproducttype",
            name="offer",
        ),
    ]
