# Generated by Django 4.2 on 2024-05-07 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0004_featuresblock_feature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="block",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="features",
                to="blocks.featuresblock",
                verbose_name="Блок",
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="icon",
            field=models.FileField(upload_to="features", verbose_name="Иконка"),
        ),
    ]
