# Generated by Django 4.2 on 2024-05-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0005_alter_feature_block_alter_feature_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featuresblock",
            name="introductory_text",
            field=models.CharField(max_length=200, verbose_name="Вводный текст"),
        ),
    ]
