# Generated by Django 4.2 on 2024-05-10 10:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0005_alter_contentblock_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="navbar",
            name="title",
        ),
    ]
