# Generated by Django 4.2.7 on 2024-07-02 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_socialnetwork"),
        ("blocks", "0005_promocatalog_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="socialmediabutton",
            name="background_color",
        ),
        migrations.RemoveField(
            model_name="socialmediabutton",
            name="icon",
        ),
        migrations.RemoveField(
            model_name="socialmediabutton",
            name="text",
        ),
        migrations.AddField(
            model_name="socialmediabutton",
            name="social_network",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.socialnetwork",
                verbose_name="Соц. сеть",
            ),
        ),
    ]
