# Generated by Django 4.2.7 on 2024-06-23 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0005_catalogproducttype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogproducttype",
            name="block",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="blocks.mainpagecatalogblock"),
        ),
    ]
