# Generated by Django 4.2 on 2024-05-13 19:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0005_alter_template_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contentblock",
            old_name="body",
            new_name="text",
        ),
        migrations.AlterField(
            model_name="cover",
            name="text",
            field=ckeditor.fields.RichTextField(max_length=1000, verbose_name="Основной текст"),
        ),
    ]
