# Generated by Django 4.2 on 2024-05-14 10:02

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0006_rename_body_contentblock_text_alter_cover_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="StagesBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True, verbose_name="Имя")),
                ("ancor", models.CharField(blank=True, max_length=50, null=True, verbose_name="Якорь")),
                ("text", ckeditor.fields.RichTextField(max_length=1000, verbose_name="Основной текст")),
                ("title", models.CharField(blank=True, max_length=100, null=True, verbose_name="Заголовок")),
                (
                    "block_relation",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="blocks.blockrelationship"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blocks.template", verbose_name="html шаблон"
                    ),
                ),
            ],
            options={
                "verbose_name": "Блок этапов",
                "verbose_name_plural": "Блоки этапов",
            },
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=100, null=True, verbose_name="Заголовок")),
                ("text", ckeditor.fields.RichTextField(max_length=1500, verbose_name="текст этапа")),
                ("period", models.CharField(max_length=200, verbose_name="срок этапа")),
                ("num", models.PositiveIntegerField(verbose_name="порядок")),
                ("block", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="blocks.stagesblock")),
            ],
            options={
                "verbose_name": "Этап",
                "verbose_name_plural": "Этапы",
            },
        ),
    ]
