# Generated by Django 4.2 on 2024-05-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0006_remove_navbar_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="url",
            field=models.CharField(max_length=50),
        ),
    ]
