# Generated by Django 4.2.7 on 2024-07-05 12:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0006_remove_socialmediabutton_background_color_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mainpagecatalogblock",
            name="add_exclusive",
        ),
        migrations.RemoveField(
            model_name="mainpagecatalogblock",
            name="button_ref",
        ),
        migrations.RemoveField(
            model_name="mainpagecatalogblock",
            name="page_title",
        ),
        migrations.AlterField(
            model_name="catalogblock",
            name="introductory_text",
            field=ckeditor.fields.RichTextField(max_length=1000, null=True, verbose_name="Введение"),
        ),
        migrations.AlterField(
            model_name="mainpagecatalogblock",
            name="introductory_text",
            field=ckeditor.fields.RichTextField(max_length=1000, null=True, verbose_name="Введение"),
        ),
    ]
