# Generated by Django 5.0 on 2024-09-10 00:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0007_remove_catalogproduct_product_catalogproduct_offer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="catalogproducttype",
            old_name="offer",
            new_name="product",
        ),
    ]
