# Generated by Django 4.2 on 2024-05-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0007_alter_feature_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cover",
            name="button_ref",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Ссылка для кнопки"),
        ),
        migrations.AlterField(
            model_name="cover",
            name="button_text",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Текст кнопки"),
        ),
        migrations.AlterField(
            model_name="cover",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="exampleblock",
            name="button_ref",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Ссылка для кнопки"),
        ),
        migrations.AlterField(
            model_name="exampleblock",
            name="button_text",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Текст кнопки"),
        ),
        migrations.AlterField(
            model_name="exampleblock",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="feature",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="featuresblock",
            name="button_ref",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Ссылка для кнопки"),
        ),
        migrations.AlterField(
            model_name="featuresblock",
            name="button_text",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Текст кнопки"),
        ),
        migrations.AlterField(
            model_name="featuresblock",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="navbar",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Заголовок"),
        ),
    ]
