# Generated by Django 4.2 on 2024-05-14 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0007_stagesblock_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stage",
            name="block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="stages", to="blocks.stagesblock"
            ),
        ),
    ]
