# Generated by Django 4.2 on 2024-05-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0007_alter_page_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentblock",
            name="image1",
            field=models.ImageField(blank=True, null=True, upload_to="images/", verbose_name="Первое изображение"),
        ),
        migrations.AlterField(
            model_name="contentblock",
            name="image2",
            field=models.ImageField(blank=True, null=True, upload_to="images/", verbose_name="Второе изображение"),
        ),
    ]
