# Generated by Django 4.2 on 2024-05-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0008_alter_cover_button_ref_alter_cover_button_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featuresblock",
            name="introductory_text",
            field=models.TextField(max_length=300, verbose_name="Вводный текст"),
        ),
    ]
