# Generated by Django 4.2.7 on 2024-07-06 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("blocks", "0008_additionalcatalogblock"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalCatalogProductType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("my_order", models.PositiveIntegerField(default=0)),
                (
                    "block",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="blocks.additionalcatalogblock"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.producttype",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "ordering": ["my_order"],
                "abstract": False,
            },
        ),
    ]
