# Generated by Django 4.2 on 2024-05-11 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0008_alter_contentblock_image1_alter_contentblock_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbar',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='navbar',
            name='logo_mobile',
        ),
    ]
