# Generated by Django 5.0 on 2024-09-10 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0008_rename_offer_catalogproducttype_product"),
        ("catalog", "0017_producttype_profit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="additionalcatalogproducttype",
            name="offer",
        ),
        migrations.AddField(
            model_name="additionalcatalogproducttype",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_catalog_product_types",
                to="catalog.producttype",
                verbose_name="Продукт",
            ),
        ),
        migrations.AlterField(
            model_name="catalogproducttype",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalog_product_types",
                to="catalog.producttype",
                verbose_name="Продукт",
            ),
        ),
    ]
