# Generated by Django 4.2 on 2024-05-09 16:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0009_alter_featuresblock_introductory_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featuresblock",
            name="introductory_text",
            field=ckeditor.fields.RichTextField(max_length=300, verbose_name="Вводный текст"),
        ),
    ]
