# Generated by Django 5.0 on 2024-09-10 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0009_remove_additionalcatalogproducttype_offer_and_more"),
        ("offers", "0002_remove_offertyperelation_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogproduct",
            name="offer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalog_product",
                to="offers.offer",
                verbose_name="Оффер",
            ),
        ),
    ]
