# Generated by Django 4.2 on 2024-05-11 20:52

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0009_remove_navbar_logo_remove_navbar_logo_mobile"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegisterBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True, verbose_name="Имя")),
                ("ancor", models.CharField(blank=True, max_length=50, null=True, verbose_name="Якорь")),
                ("title", models.CharField(blank=True, max_length=100, null=True, verbose_name="Заголовок")),
                ("explanation_text", ckeditor.fields.RichTextField(max_length=1000, verbose_name="текст пояснений")),
                ("warning_text", models.CharField(max_length=500, verbose_name="текст предупреждения")),
                (
                    "block_relation",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="blocks.blockrelationship"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blocks.template", verbose_name="html шаблон"
                    ),
                ),
            ],
            options={
                "verbose_name": "Блок регистрации",
                "verbose_name_plural": "Блоки регистрации",
            },
        ),
    ]
