# Generated by Django 4.2 on 2024-05-09 16:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0010_alter_featuresblock_introductory_text"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="exampleblock",
            table="exampleblock",
        ),
    ]
