# Generated by Django 4.2 on 2024-05-12 11:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0010_registerblock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registerblock",
            name="explanation_text",
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True, verbose_name="текст пояснений"),
        ),
    ]
