# Generated by Django 4.2.7 on 2024-07-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0010_alter_additionalcatalogblock_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="additionalcatalogblock",
            name="add_annotation",
            field=models.BooleanField(default=True, verbose_name="добавлять аннотацию к карточке"),
        ),
        migrations.AddField(
            model_name="additionalcatalogblock",
            name="add_button",
            field=models.BooleanField(default=True, verbose_name="добавлять кнопку к карточке"),
        ),
    ]
