# Generated by Django 5.0 on 2024-09-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0011_alter_catalogproduct_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogblock",
            name="add_category",
            field=models.BooleanField(null=True, verbose_name="Показывать категорию"),
        ),
    ]
