# Generated by Django 4.2 on 2024-05-09 16:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0009_remove_featurescustomstyles_sub_header_color_and_more"),
        ("blocks", "0011_alter_exampleblock_table"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ExampleBlock",
            new_name="ContentBlock",
        ),
    ]
