# Generated by Django 4.2 on 2024-05-12 14:41

import ckeditor.fields
import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0011_alter_registerblock_explanation_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMediaBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True, verbose_name="Имя")),
                ("ancor", models.CharField(blank=True, max_length=50, null=True, verbose_name="Якорь")),
                ("title", models.CharField(blank=True, max_length=100, null=True, verbose_name="Заголовок")),
                (
                    "text",
                    ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True, verbose_name="Вводный текст"),
                ),
                (
                    "block_relation",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="blocks.blockrelationship"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blocks.template", verbose_name="html шаблон"
                    ),
                ),
            ],
            options={
                "verbose_name": "Блоки подписок на соц сети",
            },
        ),
        migrations.CreateModel(
            name="SocialMediaButton",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("icon", models.ImageField(upload_to="images/social", verbose_name="Изображение")),
                (
                    "background_color",
                    colorfield.fields.ColorField(
                        default="#FFFFFF", image_field=None, max_length=25, samples=None, verbose_name="Цвет фона"
                    ),
                ),
                ("ref", models.CharField(max_length=500, verbose_name="Ссылка на соц. сети")),
                ("block", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="blocks.socialmediablock")),
            ],
            options={
                "verbose_name": "Социальная сеть",
                "verbose_name_plural": "Социальные сети",
            },
        ),
    ]
