# Generated by Django 4.2.7 on 2024-07-07 17:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0012_feature_ref"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="catalogblock",
            options={"verbose_name": "каталог", "verbose_name_plural": "каталог"},
        ),
        migrations.AlterModelOptions(
            name="contentblock",
            options={"verbose_name": "Контент", "verbose_name_plural": "Контент"},
        ),
        migrations.AlterModelOptions(
            name="featuresblock",
            options={"verbose_name": "Особенности", "verbose_name_plural": "Особенности"},
        ),
        migrations.AlterModelOptions(
            name="mainpagecatalogblock",
            options={"verbose_name": "Витрина", "verbose_name_plural": "Витрина"},
        ),
        migrations.AlterModelOptions(
            name="navbar",
            options={"verbose_name": "навбар", "verbose_name_plural": "навбары"},
        ),
        migrations.AlterModelOptions(
            name="promocatalog",
            options={"verbose_name": "Промо", "verbose_name_plural": "Промо"},
        ),
        migrations.AlterModelOptions(
            name="questionsblock",
            options={"verbose_name": "Вопросы", "verbose_name_plural": "Вопросы"},
        ),
        migrations.AlterModelOptions(
            name="registerblock",
            options={"verbose_name": "Регистрации", "verbose_name_plural": "Регистрация"},
        ),
        migrations.AlterModelOptions(
            name="socialmediablock",
            options={"verbose_name": "Соцсети", "verbose_name_plural": "Соцсети"},
        ),
        migrations.AlterModelOptions(
            name="stagesblock",
            options={"verbose_name": "Этапы", "verbose_name_plural": "Этапы"},
        ),
        migrations.AlterModelOptions(
            name="template",
            options={"verbose_name": "шаблон", "verbose_name_plural": "шаблоны"},
        ),
        migrations.AlterModelTable(
            name="catalogblock",
            table=None,
        ),
    ]
