# Generated by Django 4.2 on 2024-05-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0013_alter_socialmediablock_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmediabutton",
            name="text",
            field=models.CharField(max_length=100, null=True, verbose_name="Текст"),
        ),
    ]
