# Generated by Django 5.0 on 2024-11-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_sitesettings_contact_info_sitesettings_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trackers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_metrics', models.CharField(max_length=10, verbose_name='Метрика: Общая')),
                ('main_domain_metrics', models.CharField(max_length=10, verbose_name='Метрика: Банкомаг')),
                ('partner_metrics', models.CharField(max_length=10, verbose_name='Метрика: Партнеры')),
                ('profile_metrics', models.CharField(max_length=10, verbose_name='Метрика: Кабинет')),
            ],
            options={
                'verbose_name': 'Трекеры',
                'verbose_name_plural': 'Трекеры',
            },
        ),
    ]
