# Generated by Django 5.0 on 2024-12-09 02:57

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="docs", verbose_name="Обложка")),
                ("title", models.CharField(max_length=300, verbose_name="Название")),
                ("text", ckeditor.fields.RichTextField(max_length=300000, verbose_name="Содержание")),
                ("name", models.CharField(blank=True, max_length=300, null=True, verbose_name="Загаловок")),
                ("slug", models.SlugField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Документ",
                "verbose_name_plural": "Документы",
            },
        ),
        migrations.CreateModel(
            name="DocumentFormatPattern",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tag", models.CharField(max_length=50, verbose_name="Тэг")),
                ("text", models.CharField(max_length=50, verbose_name="Текст")),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        choices=[("openUserForm", "openUserForm"), ("openUpdateProductForm", "openUpdateProductForm")],
                        max_length=50,
                        null=True,
                        verbose_name="Метод",
                    ),
                ),
                ("arg", models.CharField(blank=True, max_length=50, null=True, verbose_name="Аргумент")),
                ("document", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="materials.document")),
            ],
            options={
                "verbose_name": "Подстановочные шаблоны",
                "verbose_name_plural": "Подстановочные шаблоны",
                "abstract": False,
            },
        ),
    ]
