# Generated by Django 5.0 on 2024-09-09 20:14

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("blocks", "0002_initial"),
        ("catalog", "0014_remove_producttype_cover_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("annotation", models.TextField(max_length=300, verbose_name="Аннотация")),
                ("description", ckeditor.fields.RichTextField(max_length=5000, verbose_name="Описание")),
                (
                    "banner",
                    models.ImageField(blank=True, null=True, upload_to="products/banners/", verbose_name="Баннер"),
                ),
                ("promote", models.DateField(blank=True, null=True, verbose_name="Продвигать до")),
                ("promotion", models.BooleanField(verbose_name="Акция")),
                ("profit", models.CharField(help_text="₽", max_length=500, verbose_name="Выгода")),
                ("start_promotion", models.DateField(blank=True, null=True, verbose_name="Начало акции")),
                ("end_promotion", models.DateField(blank=True, null=True, verbose_name="Окончание акции")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Черновик", "Черновик"), ("Архив", "Архив"), ("Опубликовано", "Опубликовано")],
                        default="Новое",
                        max_length=50,
                        verbose_name="статус",
                    ),
                ),
                (
                    "terms_of_the_promotion",
                    models.URLField(blank=True, max_length=1000, null=True, verbose_name="условия акции"),
                ),
                (
                    "partner_program",
                    models.CharField(
                        choices=[
                            ("Приведи друга", "Приведи друга"),
                            ("CPA сеть", "CPA сеть"),
                            ("Друзья/CPA", "Друзья/CPA"),
                            ("Только админ", "Только админ"),
                            ("Нет", "Нет"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Партнерская программа",
                    ),
                ),
                (
                    "verification_of_registration",
                    models.BooleanField(default=False, verbose_name="Верификация оформления"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.product", verbose_name="Продукт"
                    ),
                ),
            ],
            options={
                "verbose_name": "продукт/акция",
                "verbose_name_plural": "продукты/акции",
                "ordering": ["end_promotion"],
            },
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.URLField(max_length=300, verbose_name="ссылка")),
                (
                    "percent",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="процент",
                    ),
                ),
                ("info", models.CharField(blank=True, max_length=300, null=True, verbose_name="Инфо")),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="links", to="offers.offer"
                    ),
                ),
            ],
            options={
                "verbose_name": "ссылки",
            },
        ),
        migrations.CreateModel(
            name="OfferType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("Опубликовано", "Опубликовано"), ("Скрыто", "Скрыто")],
                        max_length=100,
                        null=True,
                        verbose_name="статус",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Название")),
                ("slug", models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name="URL")),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("image", models.ImageField(null=True, upload_to="organizations/covers", verbose_name="Этикетка")),
                ("description", ckeditor.fields.RichTextField(max_length=1000, verbose_name="Аннотация")),
                (
                    "cover",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="blocks.cover",
                        verbose_name="блок обложки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип продукта/акции",
                "verbose_name_plural": "Типы продукта/акции",
            },
        ),
        migrations.CreateModel(
            name="OfferTypeRelation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("profit", models.CharField(max_length=500, verbose_name="Выгода")),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="types",
                        to="catalog.product",
                        verbose_name="Тип продукта",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="offers.offertype",
                        verbose_name="продукт",
                    ),
                ),
            ],
        ),
    ]
