# Generated by Django 5.0 on 2024-09-09 20:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0006_additionalcatalogproducttype_offer_and_more"),
        ("offers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offertyperelation",
            name="type",
        ),
        migrations.RemoveField(
            model_name="offertyperelation",
            name="product",
        ),
        migrations.AlterModelOptions(
            name="offer",
            options={"ordering": ["end_promotion"], "verbose_name": "оффер", "verbose_name_plural": "офферы"},
        ),
        migrations.DeleteModel(
            name="OfferType",
        ),
        migrations.DeleteModel(
            name="OfferTypeRelation",
        ),
    ]
