# Generated by Django 5.0 on 2024-09-10 19:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0011_alter_catalogproduct_offer"),
        ("offers", "0003_offer_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="product",
        ),
        migrations.DeleteModel(
            name="Link",
        ),
        migrations.DeleteModel(
            name="Offer",
        ),
    ]
