# Generated by Django 4.2 on 2024-08-02 19:42

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlockRelationship",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("block_name", models.CharField(max_length=50, unique=True, verbose_name="Имя компонента")),
                ("block", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Блок",
                "verbose_name_plural": "Блоки",
                "ordering": ["block_name"],
            },
        ),
        migrations.CreateModel(
            name="SocialNetwork",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("domain", models.CharField(max_length=100, verbose_name="Домен")),
                ("icon", models.ImageField(upload_to="images/social/icons/", verbose_name="иконка")),
                (
                    "button_color",
                    colorfield.fields.ColorField(
                        default="#FFFFFF", image_field=None, max_length=25, samples=None, verbose_name="Цвет кнопки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Социальная сеть",
                "verbose_name_plural": "Социальные сети",
            },
        ),
    ]
