# Generated by Django 4.2.7 on 2024-07-02 12:10

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialNetwork",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("domain", models.CharField(max_length=100, verbose_name="Домен")),
                ("icon", models.ImageField(upload_to="images/social/icons/", verbose_name="иконка")),
                (
                    "button_color",
                    colorfield.fields.ColorField(
                        default="#FFFFFF", image_field=None, max_length=25, samples=None, verbose_name="Цвет кнопки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Социальная сеть",
                "verbose_name_plural": "Социальные сети",
            },
        ),
    ]
