# Generated by Django 4.2.7 on 2024-06-02 18:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="blockrelationship",
            table=None,
        ),
    ]
