# Generated by Django 4.2.7 on 2024-07-07 17:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_socialnetwork"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blockrelationship",
            options={"ordering": ["block_name"], "verbose_name": "Блок", "verbose_name_plural": "Блоки"},
        ),
    ]
