# Generated by Django 4.2 on 2024-04-18 19:26

import django.db.models.deletion
from django.db import migrations, models

import cms.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlocksName",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True, verbose_name="Имя компонента")),
            ],
            options={
                "verbose_name": "Имя компонента",
                "verbose_name_plural": "Имена компонентов",
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=50, verbose_name="Заголовок")),
                ("url", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Страница",
                "verbose_name_plural": "Страницы",
                "ordering": ["url"],
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="Название шаблона")),
                (
                    "file",
                    models.CharField(
                        max_length=50,
                        validators=[cms.validators.validate_html_filename],
                        verbose_name="Название файла (например base.html)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Html шаблон",
                "verbose_name_plural": "Html шаблоны",
            },
        ),
        migrations.CreateModel(
            name="Navbar",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True, verbose_name="Имя")),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("blocks_name", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cms.blocksname")),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cms.template", verbose_name="html шаблон"
                    ),
                ),
            ],
            options={
                "verbose_name": "навбар",
                "verbose_name_plural": "навбар`ы",
            },
        ),
        migrations.CreateModel(
            name="ExampleBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True, verbose_name="Имя")),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("body", models.TextField(max_length=1000, verbose_name="Основной текст")),
                ("image1", models.ImageField(upload_to="images/", verbose_name="Первое изображение")),
                ("image2", models.ImageField(upload_to="images/", verbose_name="Второе изображение")),
                ("blocks_name", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cms.blocksname")),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cms.template", verbose_name="html шаблон"
                    ),
                ),
            ],
            options={
                "verbose_name": "Контентный блок",
                "verbose_name_plural": "Контентные блоки",
            },
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("my_order", models.PositiveIntegerField(default=0)),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_block",
                        to="cms.blocksname",
                        verbose_name="Блок",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="cms.page",
                        verbose_name="Страница",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блок",
                "verbose_name_plural": "Блоки",
                "ordering": ["my_order"],
            },
        ),
    ]
