# Generated by Django 4.2 on 2024-04-18 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Component",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, null=True)),
                ("my_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["my_order"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=50)),
                ("url", models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                "ordering": ["url"],
            },
        ),
        migrations.CreateModel(
            name="Navbar",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("template", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=100)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="navcomponent", to="cms.component"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExampleComponent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("template", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=100)),
                ("body", models.TextField(max_length=1000)),
                ("image1", models.ImageField(upload_to="images/")),
                ("image2", models.ImageField(upload_to="images/")),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="excomponent", to="cms.component"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="component",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="components", to="cms.page"
            ),
        ),
    ]
