# Generated by Django 4.2 on 2024-04-19 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommonBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
        ),
        migrations.AddField(
            model_name="exampleblock",
            name="common_block",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="cms.commonblock"),
        ),
        migrations.AddField(
            model_name="navbar",
            name="common_block",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="cms.commonblock"),
        ),
    ]
