# Generated by Django 4.2 on 2024-04-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0002_commonblock_exampleblock_common_block_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exampleblock",
            name="common_block",
        ),
        migrations.RemoveField(
            model_name="navbar",
            name="common_block",
        ),
        migrations.AddField(
            model_name="blocksname",
            name="type",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name="CommonBlock",
        ),
    ]
