# Generated by Django 4.2 on 2024-04-19 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0003_remove_exampleblock_common_block_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blocksname",
            name="blocks_id",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="blocksname",
            name="class_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="exampleblock",
            name="blocks_name",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="cms.blocksname"),
        ),
        migrations.AlterField(
            model_name="navbar",
            name="blocks_name",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="cms.blocksname"),
        ),
    ]
