# Generated by Django 5.0 on 2025-07-13 04:35

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50, verbose_name='домен')),
                ('is_partners', models.BooleanField(default=True, verbose_name='партнёрский сайт')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'домен',
                'verbose_name_plural': 'домены',
            },
        ),
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя шрифта')),
                ('link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка для подключения')),
            ],
            options={
                'verbose_name': 'Шрифт',
                'verbose_name_plural': 'Шрифты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GlobalStyles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'стили',
                'verbose_name_plural': 'стили',
            },
        ),
        migrations.CreateModel(
            name='LandingDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50, verbose_name='домен')),
            ],
            options={
                'verbose_name': 'домен для лендинга',
                'verbose_name_plural': 'домены для лендинга',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disable_partners_sites', models.BooleanField(default=False, verbose_name='Отключить партнёрский домен')),
                ('default_users_font_size', models.PositiveSmallIntegerField(choices=[(6, 6), (8, 8), (9, 9), (10, 10), (12, 12), (14, 14), (18, 18), (24, 24), (30, 30), (36, 36), (48, 48), (60, 60), (72, 72)], null=True, verbose_name='Размер пользовательского шрифта по умолчанию')),
                ('owner', models.CharField(max_length=150, null=True, verbose_name='Владелец')),
                ('contact_info', models.CharField(max_length=200, null=True, verbose_name='Контактная информация')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='сайт создан')),
            ],
            options={
                'verbose_name': 'Айдентика',
                'verbose_name_plural': 'Айдентика',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('domain', models.CharField(max_length=100, verbose_name='Домен')),
                ('icon', models.ImageField(upload_to='images/social/icons/', verbose_name='иконка')),
                ('button_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Цвет кнопки')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
        migrations.CreateModel(
            name='Trackers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_metrics', models.CharField(max_length=10, verbose_name='Метрика: Общая')),
                ('main_domain_metrics', models.CharField(max_length=10, verbose_name='Метрика: Банкомаг')),
                ('partner_metrics', models.CharField(max_length=10, verbose_name='Метрика: Партнеры')),
                ('profile_metrics', models.CharField(max_length=10, verbose_name='Метрика: Кабинет')),
            ],
            options={
                'verbose_name': 'Трекеры',
                'verbose_name_plural': 'Трекеры',
            },
        ),
        migrations.CreateModel(
            name='UserFont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя шрифта')),
                ('link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка для подключения')),
            ],
            options={
                'verbose_name': 'Бренд шрифт',
                'verbose_name_plural': 'Бренд шрифты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/logo', verbose_name='Изображение')),
                ('width', models.CharField(max_length=20, verbose_name='Ширина')),
                ('height', models.CharField(max_length=20, verbose_name='Высота')),
                ('width_mobile', models.CharField(max_length=20, verbose_name='Ширина(смартфон)')),
                ('height_mobile', models.CharField(max_length=20, verbose_name='Высота(смартфон)')),
                ('settings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logo', to='settings.sitesettings')),
            ],
            options={
                'verbose_name': 'Логотип',
                'verbose_name_plural': 'Логотип',
            },
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/icon', verbose_name='Изображение')),
                ('settings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='icon', to='settings.sitesettings')),
            ],
            options={
                'verbose_name': 'Иконка',
                'verbose_name_plural': 'Иконка',
            },
        ),
        migrations.CreateModel(
            name='FormLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/logo', verbose_name='Изображение')),
                ('width', models.CharField(max_length=20, verbose_name='Ширина')),
                ('height', models.CharField(max_length=20, verbose_name='Высота')),
                ('width_mobile', models.CharField(max_length=20, verbose_name='Ширина(смартфон)')),
                ('height_mobile', models.CharField(max_length=20, verbose_name='Высота(смартфон)')),
                ('settings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form_logo', to='settings.sitesettings')),
            ],
            options={
                'verbose_name': 'Логотип для форм',
                'verbose_name_plural': 'Логотип для форм',
            },
        ),
        migrations.CreateModel(
            name='Messanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.socialnetwork', verbose_name='Соц. сеть')),
            ],
            options={
                'verbose_name': 'Мессенджер',
                'verbose_name_plural': 'Мессенджеры',
            },
        ),
    ]
