# Generated by Django 5.0 on 2024-10-31 02:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="contact_info",
            field=models.CharField(max_length=200, null=True, verbose_name="Контактная информация"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name="сайт создан"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="owner",
            field=models.CharField(max_length=150, null=True, verbose_name="Владелец"),
        ),
    ]
