# Generated by Django 5.0 on 2024-12-13 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0003_trackers"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandingDomain",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("domain", models.CharField(max_length=50, verbose_name="домен")),
            ],
            options={
                "verbose_name": "домен для лендинга",
                "verbose_name_plural": "домены для лендинга",
            },
        ),
    ]
