# Generated by Django 4.2 on 2024-08-21 17:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="docs", verbose_name="Обложка")),
                ("title", models.CharField(max_length=300, verbose_name="Заголовок")),
                ("text", ckeditor.fields.RichTextField(max_length=7000, verbose_name="Содержание")),
                ("slug", models.SlugField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Документ",
                "verbose_name_plural": "Документы",
                "db_table": "account_document",
            },
        ),
    ]
