# Generated by Django 4.2 on 2024-09-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0003_document_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="name",
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="Загаловок"),
        ),
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(max_length=300, verbose_name="Название"),
        ),
    ]
