# Generated by Django 5.0 on 2024-09-09 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionalcatalogproducttype",
            name="product",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="offers.offertype", verbose_name="Продукт"
            ),
        ),
        migrations.AlterField(
            model_name="catalogblock",
            name="product_type",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="offers.offertype"),
        ),
        migrations.AlterField(
            model_name="catalogproducttype",
            name="product",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="offers.offertype", verbose_name="Продукт"
            ),
        ),
    ]
