# Generated by Django 5.0 on 2024-09-09 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0005_remove_additionalcatalogproducttype_offer_and_more"),
        ("catalog", "0016_producttype_producttyperelation"),
    ]

    operations = [
        migrations.AddField(
            model_name="additionalcatalogproducttype",
            name="offer",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="catalog.producttype", verbose_name="Продукт"
            ),
        ),
        migrations.AddField(
            model_name="catalogproducttype",
            name="offer",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="catalog.producttype", verbose_name="Продукт"
            ),
        ),
        migrations.AlterField(
            model_name="catalogblock",
            name="product_type",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="catalog.producttype"),
        ),
    ]
