# Generated by Django 5.0 on 2024-10-23 03:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0012_catalogblock_add_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuresblock',
            name='introductory_text',
            field=ckeditor.fields.RichTextField(blank=True, max_length=300, null=True, verbose_name='Вводный текст'),
        ),
    ]
