# Generated by Django 5.0 on 2024-10-23 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0013_alter_featuresblock_introductory_text"),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navmenuitem",
            name="navbar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="menu_items", to="blocks.navbar"
            ),
        ),
        migrations.CreateModel(
            name="Footer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True, verbose_name="Имя")),
                ("ancor", models.CharField(blank=True, max_length=50, null=True, verbose_name="Якорь")),
                ("text1", models.TextField(max_length=1000)),
                ("text2", models.TextField(max_length=1000)),
                ("text3", models.TextField(max_length=1000)),
                (
                    "block_relation",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="common.blockrelationship"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blocks.template", verbose_name="html шаблон"
                    ),
                ),
            ],
            options={
                "verbose_name": "Футер",
                "verbose_name_plural": "Футер",
            },
        ),
        migrations.CreateModel(
            name="FooterMenuItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("button_text", models.CharField(blank=True, max_length=20, null=True, verbose_name="Текст кнопки")),
                (
                    "button_ref",
                    models.CharField(blank=True, max_length=20, null=True, verbose_name="Ссылка для кнопки"),
                ),
                (
                    "footer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="menu_items", to="blocks.footer"
                    ),
                ),
            ],
        ),
    ]
