# Generated by Django 4.2.7 on 2024-06-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("domen", models.CharField(max_length=50, verbose_name="домен")),
                ("logo", models.ImageField(upload_to="images/logo", verbose_name="Лого")),
                ("logo2", models.ImageField(upload_to="images/logo", verbose_name="Лого для форм")),
                ("is_active", models.BooleanField(default=True, verbose_name="активный")),
            ],
        ),
    ]
