# Generated by Django 4.2 on 2024-08-02 19:42

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("domain", models.CharField(max_length=50, verbose_name="домен")),
                ("is_partners", models.BooleanField(default=True, verbose_name="партнёрский сайт")),
            ],
            options={
                "verbose_name": "домен",
                "verbose_name_plural": "домены",
            },
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subdomain", models.CharField(max_length=50, unique=True, verbose_name="поддомен")),
                ("logo", models.ImageField(blank=True, null=True, upload_to="images/logo", verbose_name="Лого")),
                ("logo_width", models.CharField(blank=True, max_length=20, null=True, verbose_name="ширина лого")),
                (
                    "logo_width_mobile",
                    models.CharField(blank=True, max_length=20, null=True, verbose_name="ширина лого(мобильный)"),
                ),
                (
                    "logo2",
                    models.ImageField(blank=True, null=True, upload_to="images/logo", verbose_name="Лого для форм"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="активный")),
                (
                    "use_default_settings",
                    models.BooleanField(default=False, verbose_name="Использовать общие настройки сайта"),
                ),
                ("advertising_channel", models.CharField(max_length=100, null=True, verbose_name="Рекламный канал")),
                (
                    "online_from",
                    models.DateField(
                        default=datetime.datetime(2024, 8, 2, 19, 42, 32, 460421, tzinfo=datetime.timezone.utc),
                        verbose_name="онлайн с",
                    ),
                ),
                ("name", models.CharField(max_length=50, null=True, verbose_name="Название сайта")),
                ("font_size", models.PositiveIntegerField(null=True, verbose_name="размер шрифта")),
                ("owner", models.CharField(max_length=150, null=True, verbose_name="Владелец")),
                ("contact_info", models.CharField(max_length=200, null=True, verbose_name="Контактная информация")),
                (
                    "domain",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="domens.domain", verbose_name="домен"
                    ),
                ),
                (
                    "font",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="account.userfont",
                        verbose_name="шрифт",
                    ),
                ),
            ],
            options={
                "verbose_name": "сайт",
                "verbose_name_plural": "сайты партнёров",
            },
        ),
    ]
