# Generated by Django 4.2.7 on 2024-06-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domens", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="site",
            options={"verbose_name": "сайт", "verbose_name_plural": "сайты"},
        ),
        migrations.AddField(
            model_name="site",
            name="advertising_channel",
            field=models.CharField(max_length=100, null=True, verbose_name="Рекламный канал"),
        ),
        migrations.AddField(
            model_name="site",
            name="logo_width",
            field=models.CharField(max_length=20, null=True, verbose_name="ширина лого"),
        ),
        migrations.AddField(
            model_name="site",
            name="logo_width_mobile",
            field=models.CharField(max_length=20, null=True, verbose_name="ширина лого(мобильный)"),
        ),
    ]
