# Generated by Django 4.2.7 on 2024-06-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domens", "0002_alter_site_options_site_advertising_channel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="use_default_settings",
            field=models.BooleanField(default=False, verbose_name="Использовать общие настройки сайта"),
        ),
    ]
