# Generated by Django 4.2.7 on 2024-06-27 09:33

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domens", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="online_from",
            field=models.DateField(
                default=datetime.datetime(2024, 6, 27, 9, 33, 2, 15298, tzinfo=datetime.timezone.utc),
                verbose_name="онлайн с",
            ),
        ),
    ]
