# Generated by Django 4.2.7 on 2024-06-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domens", "0003_site_use_default_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("domain", models.CharField(max_length=50, verbose_name="домен")),
            ],
            options={
                "verbose_name": "домены",
            },
        ),
        migrations.AlterModelOptions(
            name="site",
            options={"verbose_name": "сайт", "verbose_name_plural": "сайты партнёров"},
        ),
    ]
