# Generated by Django 4.2.7 on 2024-06-15 10:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("domens", "0004_domain_alter_site_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="domain",
            options={"verbose_name": "домен", "verbose_name_plural": "домены"},
        ),
        migrations.RenameField(
            model_name="site",
            old_name="domen",
            new_name="subdomain",
        ),
    ]
