# Generated by Django 4.2.7 on 2024-06-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domens", "0005_alter_domain_options_rename_domen_site_subdomain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="subdomain",
            field=models.CharField(max_length=50, verbose_name="поддомен"),
        ),
    ]
