# Generated by Django 4.2.7 on 2024-06-15 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domens", "0006_alter_site_subdomain"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="domain",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="domens.domain", verbose_name="домен"
            ),
        ),
    ]
