# Generated by Django 4.2.7 on 2024-07-03 19:48

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_usersocialnetwork"),
        ("domens", "0007_alter_site_online_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="contact_info",
            field=models.CharField(max_length=200, null=True, verbose_name="Контактная информация"),
        ),
        migrations.AddField(
            model_name="site",
            name="font",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="account.userfont", verbose_name="шрифт"
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="font_size",
            field=models.PositiveIntegerField(null=True, verbose_name="размер шрифта"),
        ),
        migrations.AddField(
            model_name="site",
            name="name",
            field=models.CharField(max_length=50, null=True, verbose_name="Название сайта"),
        ),
        migrations.AddField(
            model_name="site",
            name="owner",
            field=models.CharField(max_length=150, null=True, verbose_name="Владелец"),
        ),
        migrations.AlterField(
            model_name="site",
            name="online_from",
            field=models.DateField(
                default=datetime.datetime(2024, 7, 3, 19, 48, 29, 627790, tzinfo=datetime.timezone.utc),
                verbose_name="онлайн с",
            ),
        ),
    ]
