# Generated by Django 4.2.7 on 2024-06-17 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_user_options_alter_user_email"),
        ("domens", "0008_alter_site_subdomain"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.user",
                verbose_name="пользователь",
            ),
        ),
    ]
