# Generated by Django 4.2.7 on 2024-06-18 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_options_alter_user_email'),
        ('domens', '0009_site_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site', to='user.user', verbose_name='пользователь'),
        ),
    ]
