# Generated by Django 4.2 on 2024-08-15 21:40

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domens", "0009_alter_site_online_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name="сайт создан"),
        ),
        migrations.AlterField(
            model_name="site",
            name="online_from",
            field=models.DateField(
                default=datetime.datetime(2024, 8, 15, 21, 40, 44, 571279, tzinfo=datetime.timezone.utc),
                verbose_name="онлайн с",
            ),
        ),
    ]
