# Generated by Django 4.2.7 on 2024-06-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domens', '0010_alter_site_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='is_partners',
            field=models.BooleanField(default=True, verbose_name='партнёрский сайт'),
        ),
    ]
