# Generated by Django 4.2 on 2024-08-21 18:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_alter_user_register_on_domain_site_and_more"),
        ("domens", "0012_alter_site_online_from"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="site",
            name="domain",
        ),
        migrations.RemoveField(
            model_name="site",
            name="font",
        ),
        migrations.RemoveField(
            model_name="site",
            name="user",
        ),
        migrations.DeleteModel(
            name="Domain",
        ),
    ]
