# Generated by Django 4.2 on 2024-08-21 18:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0009_delete_userfont_alter_usermessanger_messanger_and_more"),
        ("user", "0006_alter_user_register_on_domain_site_and_more"),
        ("domens", "0013_remove_site_domain_remove_site_font_remove_site_user_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Site",
        ),
    ]
