# Generated by Django 5.0 on 2025-07-19 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("blocks", "0001_initial"),
        ("catalog", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="additionalcatalogproducttype",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_catalog_product_types",
                to="catalog.producttype",
                verbose_name="Продукт",
            ),
        ),
        migrations.AddField(
            model_name="block",
            name="content_type",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
            ),
        ),
        migrations.AddField(
            model_name="catalogblock",
            name="product_type",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="catalog.producttype"),
        ),
        migrations.AddField(
            model_name="catalogproduct",
            name="block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="products", to="blocks.catalogblock"
            ),
        ),
        migrations.AddField(
            model_name="catalogproduct",
            name="offer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalog_product",
                to="catalog.offer",
                verbose_name="Оффер",
            ),
        ),
        migrations.AddField(
            model_name="catalogproducttype",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalog_product_types",
                to="catalog.producttype",
                verbose_name="Продукт",
            ),
        ),
        migrations.AddField(
            model_name="feature",
            name="block",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="features",
                to="blocks.featuresblock",
                verbose_name="Блок",
            ),
        ),
        migrations.AddField(
            model_name="footermenuitem",
            name="footer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="menu_items", to="blocks.footer"
            ),
        ),
        migrations.AddField(
            model_name="landing",
            name="domain",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="settings.landingdomain"
            ),
        ),
        migrations.AddField(
            model_name="landingblock",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocks",
                to="blocks.landing",
                verbose_name="Страница",
            ),
        ),
        migrations.AddField(
            model_name="catalogproducttype",
            name="block",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="blocks.mainpagecatalogblock"),
        ),
        migrations.AddField(
            model_name="navmenuitem",
            name="navbar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="menu_items", to="blocks.navbar"
            ),
        ),
        migrations.AddField(
            model_name="block",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocks",
                to="blocks.page",
                verbose_name="Страница",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="questions", to="blocks.questionsblock"
            ),
        ),
        migrations.AddField(
            model_name="socialmediabutton",
            name="block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="buttons", to="blocks.socialmediablock"
            ),
        ),
        migrations.AddField(
            model_name="socialmediabutton",
            name="social_network",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="settings.socialnetwork",
                verbose_name="Соц. сеть",
            ),
        ),
        migrations.AddField(
            model_name="stage",
            name="block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="stages", to="blocks.stagesblock"
            ),
        ),
        migrations.AddField(
            model_name="stagesblock",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blocks.template", verbose_name="html шаблон"
            ),
        ),
        migrations.AddField(
            model_name="socialmediablock",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blocks.template", verbose_name="html шаблон"
            ),
        ),
        migrations.AddField(
            model_name="registerblock",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blocks.template", verbose_name="html шаблон"
            ),
        ),
        migrations.AddField(
            model_name="questionsblock",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blocks.template", verbose_name="html шаблон"
            ),
        ),
        migrations.AddField(
            model_name="promocatalog",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blocks.template", verbose_name="html шаблон"
            ),
        ),
        migrations.AddField(
            model_name="navbar",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blocks.template", verbose_name="html шаблон"
            ),
        ),
        migrations.AddField(
            model_name="mainpagecatalogblock",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blocks.template", verbose_name="html шаблон"
            ),
        ),
        migrations.AddField(
            model_name="footer",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blocks.template", verbose_name="html шаблон"
            ),
        ),
        migrations.AddField(
            model_name="featuresblock",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blocks.template", verbose_name="html шаблон"
            ),
        ),
        migrations.AddField(
            model_name="cover",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blocks.template", verbose_name="html шаблон"
            ),
        ),
        migrations.AddField(
            model_name="contentblock",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blocks.template", verbose_name="html шаблон"
            ),
        ),
        migrations.AddField(
            model_name="catalogblock",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blocks.template", verbose_name="html шаблон"
            ),
        ),
        migrations.AddField(
            model_name="additionalcatalogblock",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blocks.template", verbose_name="html шаблон"
            ),
        ),
    ]
