# Generated by Django 5.0 on 2024-09-10 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0006_additionalcatalogproducttype_offer_and_more"),
        ("catalog", "0017_producttype_profit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="catalogproduct",
            name="product",
        ),
        migrations.AddField(
            model_name="catalogproduct",
            name="offer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalog_product",
                to="catalog.product",
                verbose_name="Оффер",
            ),
        ),
    ]
