# Generated by Django 5.0 on 2024-12-13 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0015_alter_footer_text1_alter_footer_text2_and_more"),
        ("common", "0001_initial"),
        ("settings", "0004_landingdomain"),
    ]

    operations = [
        migrations.CreateModel(
            name="Landing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=50, verbose_name="Заголовок")),
                ("url", models.CharField(blank=True, max_length=50, null=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="images/logo", verbose_name="Лого")),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                (
                    "domain",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="settings.landingdomain"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LandingBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("my_order", models.PositiveIntegerField(default=0)),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="landing_block",
                        to="common.blockrelationship",
                        verbose_name="Блок",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="blocks.landing",
                        verbose_name="Страница",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блок",
                "verbose_name_plural": "Блоки",
                "ordering": ["my_order"],
                "abstract": False,
            },
        ),
    ]
