# Generated by Django 5.0 on 2024-09-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0002_remove_offertyperelation_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="name",
            field=models.CharField(max_length=100, null=True, verbose_name="Название"),
        ),
    ]
