# Generated by Django 5.0 on 2024-09-09 20:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0013_alter_product_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producttype",
            name="cover",
        ),
        migrations.RemoveField(
            model_name="producttyperelation",
            name="type",
        ),
        migrations.RemoveField(
            model_name="producttyperelation",
            name="product",
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "продукт/акция", "verbose_name_plural": "продукты/акции"},
        ),
        migrations.RemoveField(
            model_name="product",
            name="annotation",
        ),
        migrations.RemoveField(
            model_name="product",
            name="banner",
        ),
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
        migrations.RemoveField(
            model_name="product",
            name="end_promotion",
        ),
        migrations.RemoveField(
            model_name="product",
            name="partner_program",
        ),
        migrations.RemoveField(
            model_name="product",
            name="profit",
        ),
        migrations.RemoveField(
            model_name="product",
            name="promote",
        ),
        migrations.RemoveField(
            model_name="product",
            name="promotion",
        ),
        migrations.RemoveField(
            model_name="product",
            name="start_promotion",
        ),
        migrations.RemoveField(
            model_name="product",
            name="status",
        ),
        migrations.RemoveField(
            model_name="product",
            name="terms_of_the_promotion",
        ),
        migrations.RemoveField(
            model_name="product",
            name="verification_of_registration",
        ),
        migrations.DeleteModel(
            name="Link",
        ),
    ]
