# Generated by Django 5.0 on 2024-09-10 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0019_rename_producttyperelation_offertyperelation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offertyperelation",
            name="offer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="types",
                to="offers.offer",
                verbose_name="Тип продукта",
            ),
        ),
    ]
