# Generated by Django 5.0 on 2024-09-16 21:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0024_remove_product_banner"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="organizationtype",
            table="catalog_organizationtype",
        ),
    ]
