# Generated by Django 4.2 on 2024-05-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/logo', verbose_name='Изображение')),
                ('width', models.CharField(max_length=20, verbose_name='Ширина')),
                ('height', models.CharField(max_length=20, verbose_name='Высота')),
                ('width_mobile', models.CharField(max_length=20, verbose_name='Ширина(смартфон)')),
                ('height_mobile', models.CharField(max_length=20, verbose_name='Высота(смартфон)')),
            ],
            options={
                'verbose_name': 'Логотип',
                'verbose_name_plural': 'Логотип',
            },
        ),
    ]
