# Generated by Django 4.2 on 2024-05-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/icon', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Иконка',
                'verbose_name_plural': 'Иконка',
            },
        ),
    ]
