# Generated by Django 4.2.7 on 2024-06-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='disable_partners_sites',
            field=models.BooleanField(default=False, verbose_name='Отключить партнёрский домен'),
        ),
    ]
