# Generated by Django 4.2 on 2024-05-13 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="icon",
            name="settings",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="icon", to="settings.sitesettings"
            ),
        ),
        migrations.AlterField(
            model_name="logo",
            name="settings",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="logo", to="settings.sitesettings"
            ),
        ),
    ]
