# Generated by Django 4.2 on 2024-08-21 18:19

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("domain", models.CharField(max_length=50, verbose_name="домен")),
                ("is_partners", models.BooleanField(default=True, verbose_name="партнёрский сайт")),
                ("name", models.CharField(blank=True, max_length=50, null=True, verbose_name="Название")),
            ],
            options={
                "verbose_name": "домен",
                "verbose_name_plural": "домены",
                "db_table": "domens_domain",
            },
        ),
        migrations.CreateModel(
            name="Font",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="Имя шрифта")),
                (
                    "link",
                    models.CharField(blank=True, max_length=250, null=True, verbose_name="Ссылка для подключения"),
                ),
            ],
            options={
                "verbose_name": "Шрифт",
                "verbose_name_plural": "Шрифты",
                "db_table": "styles_font",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GlobalStyles",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "verbose_name": "стили",
                "verbose_name_plural": "стили",
                "db_table": "styles_globalstyles",
            },
        ),
        migrations.CreateModel(
            name="SocialNetwork",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("domain", models.CharField(max_length=100, verbose_name="Домен")),
                ("icon", models.ImageField(upload_to="images/social/icons/", verbose_name="иконка")),
                (
                    "button_color",
                    colorfield.fields.ColorField(
                        default="#FFFFFF", image_field=None, max_length=25, samples=None, verbose_name="Цвет кнопки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Социальная сеть",
                "verbose_name_plural": "Социальные сети",
                "db_table": "common_socialnetwork",
            },
        ),
        migrations.CreateModel(
            name="UserFont",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="Имя шрифта")),
                (
                    "link",
                    models.CharField(blank=True, max_length=250, null=True, verbose_name="Ссылка для подключения"),
                ),
            ],
            options={
                "verbose_name": "Бренд шрифт",
                "verbose_name_plural": "Бренд шрифты",
                "db_table": "account_userfont",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="sitesettings",
            options={"verbose_name": "Айдентика", "verbose_name_plural": "Айдентика"},
        ),
        migrations.CreateModel(
            name="Messanger",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "social_network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="settings.socialnetwork",
                        verbose_name="Соц. сеть",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мессенджер",
                "verbose_name_plural": "Мессенджеры",
                "db_table": "account_messanger",
            },
        ),
    ]
