# Generated by Django 4.2 on 2024-05-14 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0002_alter_icon_settings_alter_logo_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormLogo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="images/logo", verbose_name="Изображение")),
                ("width", models.CharField(max_length=20, verbose_name="Ширина")),
                ("height", models.CharField(max_length=20, verbose_name="Высота")),
                ("width_mobile", models.CharField(max_length=20, verbose_name="Ширина(смартфон)")),
                ("height_mobile", models.CharField(max_length=20, verbose_name="Высота(смартфон)")),
                (
                    "settings",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_logo",
                        to="settings.sitesettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Логотип для форм",
                "verbose_name_plural": "Логотип для форм",
            },
        ),
    ]
