# Generated by Django 5.0 on 2024-09-24 21:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="additionalcatalogcustomstyles",
            options={},
        ),
        migrations.AlterModelOptions(
            name="catalogcustomstyles",
            options={},
        ),
        migrations.AlterModelOptions(
            name="contentcustomstyles",
            options={},
        ),
        migrations.AlterModelOptions(
            name="covercustomstyles",
            options={},
        ),
        migrations.AlterModelOptions(
            name="featurescustomstyles",
            options={},
        ),
        migrations.AlterModelOptions(
            name="mainpagecatalogcustomstyles",
            options={},
        ),
        migrations.AlterModelOptions(
            name="navbarcustomstyles",
            options={},
        ),
        migrations.AlterModelOptions(
            name="promocatalogcustomstyles",
            options={},
        ),
        migrations.AlterModelOptions(
            name="questionscustomstyles",
            options={},
        ),
        migrations.AlterModelOptions(
            name="registercustomstyles",
            options={},
        ),
        migrations.AlterModelOptions(
            name="socialcustomstyles",
            options={},
        ),
        migrations.AlterModelOptions(
            name="stagescustomstyles",
            options={},
        ),
    ]
