# Generated by Django 5.0 on 2024-10-26 19:57

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0003_footercustomstyles"),
    ]

    operations = [
        migrations.AddField(
            model_name="additionalcatalogcustomstyles",
            name="refs_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
                verbose_name="Цвет ссылок",
            ),
        ),
        migrations.AddField(
            model_name="catalogcustomstyles",
            name="refs_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
                verbose_name="Цвет ссылок",
            ),
        ),
        migrations.AddField(
            model_name="contentcustomstyles",
            name="refs_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
                verbose_name="Цвет ссылок",
            ),
        ),
        migrations.AddField(
            model_name="covercustomstyles",
            name="refs_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
                verbose_name="Цвет ссылок",
            ),
        ),
        migrations.AddField(
            model_name="featurescustomstyles",
            name="refs_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
                verbose_name="Цвет ссылок",
            ),
        ),
        migrations.AddField(
            model_name="footercustomstyles",
            name="refs_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
                verbose_name="Цвет ссылок",
            ),
        ),
        migrations.AddField(
            model_name="mainpagecatalogcustomstyles",
            name="refs_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
                verbose_name="Цвет ссылок",
            ),
        ),
        migrations.AddField(
            model_name="navbarcustomstyles",
            name="refs_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
                verbose_name="Цвет ссылок",
            ),
        ),
        migrations.AddField(
            model_name="promocatalogcustomstyles",
            name="refs_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
                verbose_name="Цвет ссылок",
            ),
        ),
        migrations.AddField(
            model_name="questionscustomstyles",
            name="refs_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
                verbose_name="Цвет ссылок",
            ),
        ),
        migrations.AddField(
            model_name="registercustomstyles",
            name="refs_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
                verbose_name="Цвет ссылок",
            ),
        ),
        migrations.AddField(
            model_name="socialcustomstyles",
            name="refs_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
                verbose_name="Цвет ссылок",
            ),
        ),
        migrations.AddField(
            model_name="stagescustomstyles",
            name="refs_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
                verbose_name="Цвет ссылок",
            ),
        ),
    ]
