# Generated by Django 5.0 on 2025-07-13 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('site_statistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useraction',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='site_statistics.useractivity'),
        ),
        migrations.AddField(
            model_name='websearcheraction',
            name='searcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='site_statistics.websearcher'),
        ),
        migrations.AddIndex(
            model_name='sessionaction',
            index=models.Index(fields=['session_id'], name='site_statis_session_e3ab7b_idx'),
        ),
        migrations.AddIndex(
            model_name='useraction',
            index=models.Index(fields=['session_id'], name='site_statis_session_c7d8f2_idx'),
        ),
    ]
