# Generated by Django 5.0 on 2025-01-02 21:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("site_statistics", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useractivity",
            name="device",
        ),
        migrations.RemoveField(
            model_name="useractivity",
            name="ip",
        ),
        migrations.RemoveField(
            model_name="useractivity",
            name="site",
        ),
    ]
