# Generated by Django 5.0 on 2025-01-02 23:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("site_statistics", "0002_remove_useractivity_device_remove_useractivity_ip_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sessionmodel",
            name="unique_key",
        ),
        migrations.RemoveField(
            model_name="useractivity",
            name="unique_key",
        ),
    ]
