# Generated by Django 5.0 on 2024-09-21 08:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0002_email2"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Email2",
        ),
    ]
