# Generated by Django 4.2 on 2024-08-15 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestUserSet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "users_count",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(300)],
                        verbose_name="Количество пользователей",
                    ),
                ),
            ],
        ),
    ]
