# Generated by Django 4.2 on 2024-08-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestUserSet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("users_count", models.PositiveSmallIntegerField(verbose_name="Количество пользователей")),
            ],
        ),
    ]
