# Generated by Django 4.2 on 2024-08-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_tests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testuserset",
            name="users_count",
            field=models.PositiveSmallIntegerField(verbose_name="Количество пользователей"),
        ),
    ]
