# Generated by Django 4.2.7 on 2024-06-01 17:52

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("logo", models.ImageField(upload_to="organizations/logos/", verbose_name="Лого")),
                ("site", models.URLField(max_length=500, verbose_name="сайт")),
                ("admin_hint", models.CharField(max_length=100, verbose_name="пояснение для админа")),
            ],
            options={
                "verbose_name": "Организация",
                "verbose_name_plural": "Организации",
            },
        ),
        migrations.CreateModel(
            name="OrganizationType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Тип оргпнизации",
                "verbose_name_plural": "Типы оргпнизаций",
            },
        ),
        migrations.CreateModel(
            name="ProductType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Название")),
                ("slug", models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name="URL")),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("cover", models.ImageField(upload_to="organizations/covers", verbose_name="Обложка")),
                ("description", models.CharField(max_length=500, verbose_name="Описание")),
                ("profit", models.CharField(max_length=500, verbose_name="Выгода")),
            ],
            options={
                "verbose_name": "Тип продукта/акции",
                "verbose_name_plural": "Типы продукта/акции",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cover", models.ImageField(upload_to="products/covers", verbose_name="Обложка")),
                ("name", models.CharField(max_length=100, verbose_name="Название продукта")),
                ("annotation", models.CharField(max_length=300, verbose_name="Аннотация")),
                ("description", ckeditor.fields.RichTextField(max_length=5000, verbose_name="Описание")),
                ("banner", models.ImageField(upload_to="products/banners/", verbose_name="Баннер")),
                ("promote", models.DateField(blank=True, null=True, verbose_name="Продвигать до")),
                (
                    "private",
                    models.BooleanField(verbose_name="Приватный(виден только зарегистрированным пользователям)"),
                ),
                ("promotion", models.BooleanField(verbose_name="Акция")),
                ("profit", models.CharField(max_length=500, verbose_name="Выгода")),
                ("start_promotion", models.DateField(blank=True, null=True, verbose_name="Начало акции")),
                ("end_promotion", models.DateField(blank=True, null=True, verbose_name="Окончание акции")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.organization",
                        verbose_name="организация",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.producttype",
                        verbose_name="Тип продукта",
                    ),
                ),
            ],
            options={
                "verbose_name": "продукт/акция",
                "verbose_name_plural": "продукты/акции",
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalog.organizationtype", verbose_name="Тип"
            ),
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.URLField(max_length=300, verbose_name="ссылка")),
                (
                    "percent",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="процент",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="links", to="catalog.product"
                    ),
                ),
            ],
            options={
                "verbose_name": "ссылки",
            },
        ),
    ]
