# Generated by Django 4.2.7 on 2024-06-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producttype",
            name="image",
            field=models.ImageField(
                null=True, upload_to="organizations/covers", verbose_name="Картинка блока типа продукта(этикетка)"
            ),
        ),
    ]
