# Generated by Django 4.2.7 on 2024-07-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exclusivecard",
            name="annotation",
            field=models.TextField(max_length=700, null=True, verbose_name="аннотация"),
        ),
        migrations.AddField(
            model_name="exclusivecard",
            name="button_ref",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Ссылка для кнопки"),
        ),
        migrations.AddField(
            model_name="exclusivecard",
            name="button_text",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Текст кнопки"),
        ),
    ]
