# Generated by Django 4.2.7 on 2024-06-04 15:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producttype",
            old_name="image2",
            new_name="image",
        ),
    ]
