# Generated by Django 4.2 on 2024-08-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("Черновик", "Черновик"), ("Архив", "Архив"), ("Опубликовано", "Опубликовано")],
                default="Новое",
                max_length=50,
                verbose_name="статус",
            ),
        ),
    ]
