# Generated by Django 4.2.7 on 2024-06-03 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_alter_blockrelationship_table"),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogPageTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=50, verbose_name="Заголовок")),
            ],
            options={
                "verbose_name": "Шаблон страницы каталога",
                "verbose_name_plural": "Шаблон страницы каталога",
            },
        ),
        migrations.AlterModelOptions(
            name="organizationtype",
            options={"verbose_name": "Тип организации", "verbose_name_plural": "Типы организаций"},
        ),
        migrations.AlterField(
            model_name="product",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="products/banners/", verbose_name="Баннер"),
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("my_order", models.PositiveIntegerField(default=0)),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalog_block",
                        to="common.blockrelationship",
                        verbose_name="Блок",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="catalog.catalogpagetemplate",
                        verbose_name="Страница",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блок",
                "verbose_name_plural": "Блоки",
                "ordering": ["my_order"],
                "abstract": False,
            },
        ),
    ]
