# Generated by Django 4.2 on 2024-08-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="terms_of_the_promotion",
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name="условия акции"),
        ),
    ]
