# Generated by Django 4.2.7 on 2024-07-07 17:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_exclusivecard_annotation_exclusivecard_button_ref_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="catalogpagetemplate",
            options={"verbose_name": "каталог", "verbose_name_plural": "каталог"},
        ),
    ]
