# Generated by Django 4.2.7 on 2024-06-22 17:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_alter_producttype_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["end_promotion"],
                "verbose_name": "продукт/акция",
                "verbose_name_plural": "продукты/акции",
            },
        ),
    ]
