# Generated by Django 4.2.7 on 2024-06-04 15:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_rename_image2_producttype_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producttype",
            name="image",
        ),
    ]
