# Generated by Django 4.2.7 on 2024-06-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_alter_product_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExclusiveCard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="images/exclusive", verbose_name="картинка")),
                ("bonus", models.CharField(max_length=50, verbose_name="бонус")),
            ],
            options={
                "verbose_name": "Карточка Эксклюзив",
                "verbose_name_plural": "Карточка Эксклюзив",
            },
        ),
    ]
