# Generated by Django 4.2.7 on 2024-06-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_remove_producttype_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producttype",
            name="cover",
            field=models.ImageField(
                null=True, upload_to="organizations/covers", verbose_name="Картинка блока типа продукта"
            ),
        ),
    ]
