# Generated by Django 4.2 on 2024-08-23 02:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_product_partner_annotation_product_partner_bonus_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="annotation",
            field=models.TextField(max_length=300, verbose_name="Аннотация"),
        ),
        migrations.AlterField(
            model_name="product",
            name="partner_annotation",
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name="Партнерская аннотация"),
        ),
        migrations.AlterField(
            model_name="product",
            name="partner_description",
            field=ckeditor.fields.RichTextField(
                blank=True, max_length=5000, null=True, verbose_name="Партнерское описание"
            ),
        ),
    ]
