# Generated by Django 4.2.7 on 2024-06-04 15:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_rename_cover_producttype_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producttype",
            old_name="image",
            new_name="cover",
        ),
    ]
