# Generated by Django 4.2 on 2024-08-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_alter_organization_admin_hint_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="partner_program",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Партнерская программа"),
        ),
    ]
