# Generated by Django 4.2.7 on 2024-06-04 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0002_catalogblock_catalogproduct"),
        ("catalog", "0007_rename_cover_producttype_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttype",
            name="cover",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="blocks.cover", verbose_name="блок обложки"
            ),
        ),
    ]
