# Generated by Django 4.2 on 2024-08-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_organization_partner_program"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttype",
            name="status",
            field=models.CharField(
                choices=[("Опубликовано", "Опубликовано"), ("Скрыто", "Скрыто")],
                max_length=100,
                null=True,
                verbose_name="статус",
            ),
        ),
    ]
