# Generated by Django 4.2.7 on 2024-06-08 13:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_producttype_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("new", "Новое"), ("published", "Опубликовано")], default="new", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="admin_hint",
            field=ckeditor.fields.RichTextField(max_length=1500, verbose_name="пояснение для админа"),
        ),
        migrations.AlterField(
            model_name="product",
            name="profit",
            field=models.CharField(help_text="₽", max_length=500, verbose_name="Выгода"),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="description",
            field=ckeditor.fields.RichTextField(max_length=1000, verbose_name="Описание"),
        ),
    ]
