# Generated by Django 4.2.7 on 2024-06-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0010_remove_product_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("Новое", "Новое"), ("Опубликовано", "Опубликовано")],
                default="Новое",
                max_length=50,
                verbose_name="статус",
            ),
        ),
    ]
