# Generated by Django 4.2.7 on 2024-06-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0011_product_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="info",
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="Инфо"),
        ),
    ]
