# Generated by Django 5.0 on 2024-09-09 20:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0003_alter_additionalcatalogproducttype_product_and_more"),
        ("catalog", "0014_remove_producttype_cover_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductType",
        ),
        migrations.DeleteModel(
            name="ProductTypeRelation",
        ),
    ]
