# Generated by Django 5.0 on 2024-09-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0016_producttype_producttyperelation"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttype",
            name="profit",
            field=models.CharField(max_length=500, null=True, verbose_name="Выгода"),
        ),
    ]
