# Generated by Django 5.0 on 2024-09-10 01:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0017_producttype_profit"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("Черновик", "Черновик"), ("Архив", "Архив"), ("Опубликовано", "Опубликовано")],
                default="Новое",
                max_length=50,
                verbose_name="статус",
            ),
        ),
    ]
