# Generated by Django 5.0 on 2024-09-10 02:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0018_product_status"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductTypeRelation",
            new_name="OfferTypeRelation",
        ),
        migrations.RenameField(
            model_name="offertyperelation",
            old_name="product",
            new_name="offer",
        ),
    ]
