# Generated by Django 5.0 on 2024-09-10 19:51

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0020_alter_offertyperelation_offer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, null=True, verbose_name="Название")),
                ("annotation", models.TextField(max_length=300, verbose_name="Аннотация")),
                ("description", ckeditor.fields.RichTextField(max_length=5000, verbose_name="Описание")),
                (
                    "banner",
                    models.ImageField(blank=True, null=True, upload_to="products/banners/", verbose_name="Баннер"),
                ),
                ("promote", models.DateField(blank=True, null=True, verbose_name="Продвигать до")),
                ("promotion", models.BooleanField(verbose_name="Акция")),
                ("profit", models.CharField(help_text="₽", max_length=500, verbose_name="Выгода")),
                ("start_promotion", models.DateField(blank=True, null=True, verbose_name="Начало акции")),
                ("end_promotion", models.DateField(blank=True, null=True, verbose_name="Окончание акции")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Черновик", "Черновик"), ("Архив", "Архив"), ("Опубликовано", "Опубликовано")],
                        default="Новое",
                        max_length=50,
                        verbose_name="статус",
                    ),
                ),
                (
                    "terms_of_the_promotion",
                    models.URLField(blank=True, max_length=1000, null=True, verbose_name="условия акции"),
                ),
                (
                    "partner_program",
                    models.CharField(
                        choices=[
                            ("Приведи друга", "Приведи друга"),
                            ("CPA сеть", "CPA сеть"),
                            ("Друзья/CPA", "Друзья/CPA"),
                            ("Только админ", "Только админ"),
                            ("Нет", "Нет"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Партнерская программа",
                    ),
                ),
                (
                    "verification_of_registration",
                    models.BooleanField(default=False, verbose_name="Верификация оформления"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.product", verbose_name="Продукт"
                    ),
                ),
            ],
            options={
                "verbose_name": "оффер",
                "verbose_name_plural": "офферы",
                "db_table": "offers_offer",
                "ordering": ["end_promotion"],
            },
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.URLField(max_length=300, verbose_name="ссылка")),
                (
                    "percent",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="процент",
                    ),
                ),
                ("info", models.CharField(blank=True, max_length=300, null=True, verbose_name="Инфо")),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="links", to="catalog.offer"
                    ),
                ),
            ],
            options={
                "verbose_name": "ссылки",
                "db_table": "offers_link",
            },
        ),
        migrations.AlterField(
            model_name="offertyperelation",
            name="offer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="types",
                to="catalog.offer",
                verbose_name="Тип продукта",
            ),
        ),
    ]
