# Generated by Django 5.0 on 2024-09-10 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0021_offer_link_alter_offertyperelation_offer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="profit",
        ),
        migrations.AddField(
            model_name="productcategory",
            name="short",
            field=models.CharField(max_length=100, null=True, verbose_name="Сокращение"),
        ),
        migrations.AlterField(
            model_name="offer",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to="catalog.product",
                verbose_name="Продукт",
            ),
        ),
    ]
