# Generated by Django 5.0 on 2025-07-13 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='название')),
                ('message', models.CharField(max_length=600, verbose_name='сообщение')),
                ('status', models.CharField(choices=[('warning', 'предупреждение'), ('error', 'ошибка'), ('info', 'информационное')], max_length=100, null=True, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'уведомление',
                'verbose_name_plural': 'уведомления',
            },
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SITECREATED', 'SITECREATED'), ('EMAILVERIFIED', 'EMAILVERIFIED'), ('SIGNEDUP', 'SIGNEDUP')], max_length=100, verbose_name='триггер')),
            ],
            options={
                'verbose_name': 'триггер',
                'verbose_name_plural': 'триггеры',
            },
        ),
        migrations.CreateModel(
            name='NotificationFormatPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, verbose_name='Тэг')),
                ('text', models.CharField(max_length=50, verbose_name='Текст')),
                ('method', models.CharField(blank=True, choices=[('openUserForm', 'openUserForm'), ('openUpdateProductForm', 'openUpdateProductForm')], max_length=50, null=True, verbose_name='Метод')),
                ('arg', models.CharField(blank=True, max_length=50, null=True, verbose_name='Аргумент')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notification')),
            ],
            options={
                'verbose_name': 'Подстановочные шаблоны',
                'verbose_name_plural': 'Подстановочные шаблоны',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='trigger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.trigger', verbose_name='триггер'),
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notification', verbose_name='уведомление')),
            ],
            options={
                'verbose_name': 'пользовательское уведомление',
                'verbose_name_plural': 'пользовательские уведомления',
            },
        ),
    ]
