# Generated by Django 4.2 on 2024-09-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_userproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="userproduct",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
