# Generated by Django 5.0 on 2024-09-12 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0010_remove_userproduct_link_useroffer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Roles",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SuperUserRole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user.roles")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
