# Generated by Django 5.0 on 2024-09-15 19:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0011_roles_superuserrole"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="roles",
            options={"verbose_name": "Роли", "verbose_name_plural": "Роли"},
        ),
    ]
