# Generated by Django 5.0 on 2024-12-09 03:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.CharField(max_length=200, verbose_name="почта")),
            ],
            options={
                "verbose_name": "Системная почта",
                "verbose_name_plural": "Системные почты",
            },
        ),
    ]
