# Generated by Django 5.0 on 2024-12-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0002_confirmphonecode"),
    ]

    operations = [
        migrations.AddField(
            model_name="confirmphonecode",
            name="phone",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
