# Generated by Django 4.2 on 2024-08-31 04:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import user.models.product


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0013_alter_product_category"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="online_from",
            field=models.DateField(default=django.utils.timezone.now, verbose_name="онлайн с"),
        ),
        migrations.CreateModel(
            name="UserProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("connected", models.DateField(null=True)),
                ("profit", models.DateField(null=True)),
                ("got", models.DateField(null=True)),
                ("connected_with_link", models.BooleanField(null=True)),
                ("redirections", models.PositiveIntegerField(default=0)),
                ("screen", models.ImageField(null=True, upload_to=user.models.product.user_directory_path)),
                ("comment", models.CharField(max_length=1000, null=True)),
                ("link", models.CharField(max_length=1000, null=True)),
                ("gain", models.PositiveIntegerField(default=0)),
                ("fully_verified", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="user_products", to="catalog.product"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользовательские продукты",
                "verbose_name_plural": "Пользовательские продукты",
            },
        ),
    ]
