# Generated by Django 4.2 on 2024-09-01 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import user.models.product


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0013_alter_product_category"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("connected", models.DateField(null=True, verbose_name="Подключен")),
                ("profit", models.DateField(null=True, verbose_name="Бонус")),
                ("got", models.DateField(null=True, verbose_name="Получен")),
                ("connected_with_link", models.BooleanField(null=True, verbose_name="Подключен по ссылке")),
                ("redirections", models.PositiveIntegerField(default=0, verbose_name="Переходы")),
                (
                    "screen",
                    models.ImageField(
                        null=True, upload_to=user.models.product.user_directory_path, verbose_name="скриншот"
                    ),
                ),
                ("comment", models.CharField(max_length=1000, null=True, verbose_name="Комментарий")),
                ("link", models.CharField(max_length=1000, null=True, verbose_name="Ссылка")),
                ("gain", models.PositiveIntegerField(default=0, verbose_name="Доход")),
                ("fully_verified", models.BooleanField(default=False, verbose_name="Полностью подтверждён")),
                ("created_at", models.DateField(auto_now_add=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_products",
                        to="catalog.product",
                        verbose_name="Продукт",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользовательские продукты",
                "verbose_name_plural": "Пользовательские продукты",
            },
        ),
    ]
