# Generated by Django 4.2.7 on 2024-06-21 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domens", "0002_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="register_on_domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="register_on_domain",
                to="domens.domain",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="register_on_subdomain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="register_on_subdomain",
                to="domens.site",
            ),
        ),
    ]
