# Generated by Django 4.2 on 2024-08-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="supersponsor",
            field=models.BooleanField(default=False, verbose_name="Главный спонсор"),
        ),
    ]
