# Generated by Django 4.2 on 2024-05-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name="пользователь создан"),
        ),
    ]
