# Generated by Django 4.2.7 on 2024-06-21 17:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_register_on_domain_user_register_on_subdomain"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="register_on_domain",
        ),
    ]
