# Generated by Django 4.2.7 on 2024-06-21 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domens", "0002_initial"),
        ("user", "0003_remove_user_register_on_domain"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="register_on_subdomain",
        ),
        migrations.AddField(
            model_name="user",
            name="register_on_site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="register_on_site",
                to="domens.site",
            ),
        ),
    ]
