# Generated by Django 4.2 on 2024-08-22 15:40

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_site_online_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="online_from",
            field=models.DateField(default=datetime.datetime(2024, 8, 22, 15, 40, 1, 134601), verbose_name="онлайн с"),
        ),
    ]
