# Generated by Django 4.2 on 2024-09-04 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_userproduct_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="Idea",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("errors", "Ошибка в работе"),
                            ("correction", "Исправление"),
                            ("modernization", "Улучшение"),
                            ("new_feature", "Новая возможность"),
                        ],
                        max_length=100,
                        verbose_name="категория",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("errors", "Ошибка в работе"),
                            ("correction", "Исправление"),
                            ("modernization", "Улучшение"),
                            ("new_feature", "Новая возможность"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="статус",
                    ),
                ),
                ("finishe_date", models.DateField(null=True)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("title", models.CharField(max_length=500, verbose_name="Тема")),
                ("description", models.CharField(max_length=5000, verbose_name="Описание")),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ideas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предложение",
                "verbose_name_plural": "Предложения",
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "idea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="likes", to="user.idea"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
