# Generated by Django 4.2.7 on 2024-06-21 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domens", "0002_initial"),
        ("user", "0004_remove_user_register_on_subdomain_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="register_on_domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="register_on_domain",
                to="domens.domain",
                verbose_name="зарегистрирован на домене",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="register_on_site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="register_on_site",
                to="domens.site",
                verbose_name="зарегистрирован на сайте",
            ),
        ),
    ]
