# Generated by Django 4.2 on 2024-08-23 02:54

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_alter_site_online_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="online_from",
            field=models.DateField(default=datetime.datetime(2024, 8, 23, 2, 54, 48, 993591), verbose_name="онлайн с"),
        ),
    ]
