# Generated by Django 4.2.7 on 2024-07-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_user_register_on_domain_alter_user_register_on_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="", verbose_name="аватарка"),
        ),
        migrations.AddField(
            model_name="user",
            name="second_name",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Фамлия"),
        ),
    ]
