# Generated by Django 4.2.7 on 2024-07-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_user_profile_picture_user_second_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_is_confirmed",
            field=models.BooleanField(default=False, verbose_name="Почта подтверждена"),
        ),
    ]
