# Generated by Django 4.2 on 2024-08-23 03:33

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_alter_site_online_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="online_from",
            field=models.DateField(default=datetime.datetime(2024, 8, 23, 3, 32, 58, 514791), verbose_name="онлайн с"),
        ),
    ]
