# Generated by Django 4.2 on 2024-09-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_ideascreen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idea",
            name="status",
            field=models.CharField(
                choices=[
                    ("errors", "Ошибка в работе"),
                    ("correction", "Исправление"),
                    ("modernization", "Улучшение"),
                    ("new_feature", "Новая возможность"),
                ],
                default="new",
                max_length=100,
                verbose_name="статус",
            ),
        ),
    ]
