# Generated by Django 4.2.7 on 2024-07-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_user_phone_is_confirmed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_is_confirmed",
            field=models.BooleanField(default=False, verbose_name="Телефон подтвержден"),
        ),
    ]
