# Generated by Django 4.2 on 2024-08-24 06:13

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0009_productcategory_remove_product_type_product_types_and_more"),
        ("user", "0008_alter_site_online_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="online_from",
            field=models.DateField(default=datetime.datetime(2024, 8, 24, 6, 13, 44, 674664), verbose_name="онлайн с"),
        ),
        migrations.CreateModel(
            name="UserProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("connected", models.DateField(null=True)),
                ("redirections", models.PositiveIntegerField(default=0)),
                ("profit", models.PositiveIntegerField(default=0)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="catalog.product")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
