# Generated by Django 4.2 on 2024-08-24 12:26

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_alter_site_online_from_userproduct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="online_from",
            field=models.DateField(default=datetime.datetime(2024, 8, 24, 12, 26, 33, 626122), verbose_name="онлайн с"),
        ),
    ]
