# Generated by Django 5.0 on 2024-09-11 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0022_remove_offer_profit_productcategory_short_and_more"),
        ("user", "0009_alter_ideascreen_idea_alter_ideascreen_screen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userproduct",
            name="link",
        ),
        migrations.CreateModel(
            name="UserOffer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("link", models.CharField(max_length=1000, verbose_name="Ссылка")),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.offer", verbose_name="оффер"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
    ]
