# Generated by Django 4.2 on 2024-08-25 13:40

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import user.models.product


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0012_alter_site_online_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="userproduct",
            name="comment",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userproduct",
            name="connected_with_link",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="userproduct",
            name="got",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="userproduct",
            name="screen",
            field=models.ImageField(null=True, upload_to=user.models.product.user_directory_path),
        ),
        migrations.AlterField(
            model_name="site",
            name="online_from",
            field=models.DateField(default=datetime.datetime(2024, 8, 25, 13, 40, 32, 849127), verbose_name="онлайн с"),
        ),
        migrations.AlterField(
            model_name="userproduct",
            name="profit",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="userproduct",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="products", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
