# Generated by Django 4.2 on 2024-04-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IconSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=20, verbose_name='Высота')),
                ('width', models.CharField(max_length=20, verbose_name='Ширина')),
            ],
            options={
                'verbose_name': 'Размер иконок',
                'verbose_name_plural': 'Размер иконок',
            },
        ),
        migrations.CreateModel(
            name='MarginBottomBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margin', models.CharField(max_length=20, verbose_name='Отступ')),
            ],
            options={
                'verbose_name': 'Отступ в блоке снизу',
                'verbose_name_plural': 'Отступ в блоке снизу',
            },
        ),
        migrations.CreateModel(
            name='MarginTopBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margin', models.CharField(max_length=20, verbose_name='Отступ')),
            ],
            options={
                'verbose_name': 'Отступ в блоке сверху',
                'verbose_name_plural': 'Отступ в блоке сверху',
            },
        ),
    ]
