# Generated by Django 4.2 on 2024-04-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_styles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarginBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margin_top', models.CharField(max_length=20, verbose_name='Отступ сверху')),
                ('margin_bottom', models.CharField(max_length=20, verbose_name='Отступ снизу')),
            ],
            options={
                'verbose_name': 'Отступы в блоке',
                'verbose_name_plural': 'Отступы в блоке',
            },
        ),
        migrations.DeleteModel(
            name='MarginBottomBlock',
        ),
        migrations.DeleteModel(
            name='MarginTopBlock',
        ),
    ]
