# Generated by Django 5.0 on 2024-12-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0014_alter_ideascreen_screen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Название сайта"),
        ),
    ]
