# Generated by Django 4.2 on 2024-08-22 15:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_product_partner_program_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="partner_annotation",
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name="Партнерская аннотация"),
        ),
        migrations.AddField(
            model_name="product",
            name="partner_bonus",
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name="Партнерский бонус"),
        ),
        migrations.AddField(
            model_name="product",
            name="partner_description",
            field=ckeditor.fields.RichTextField(
                blank=True, max_length=5000, null=True, verbose_name="Партнерский бонус"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="verification_of_registration",
            field=models.BooleanField(default=False, verbose_name="Верификация оформления"),
        ),
    ]
