# Generated by Django 4.2 on 2024-08-24 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_producttype_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Категория")),
            ],
            options={
                "verbose_name": "Категория продуктов",
                "verbose_name_plural": "Категории продуктов",
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="type",
        ),
        migrations.AddField(
            model_name="product",
            name="types",
            field=models.ManyToManyField(
                related_name="products", to="catalog.producttype", verbose_name="Тип продукта"
            ),
        ),
        migrations.AddField(
            model_name="producttype",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.productcategory",
                verbose_name="категория",
            ),
        ),
    ]
