# Generated by Django 4.2 on 2024-08-24 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0009_productcategory_remove_product_type_product_types_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="types",
        ),
        migrations.CreateModel(
            name="ProductTypeRelation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="types",
                        to="catalog.product",
                        verbose_name="Тип продукта",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.producttype",
                        verbose_name="продукт",
                    ),
                ),
            ],
        ),
    ]
