# Generated by Django 5.0 on 2024-09-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0022_remove_offer_profit_productcategory_short_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="products/banners/", verbose_name="Баннер"),
        ),
    ]
