# Generated by Django 4.2 on 2024-04-21 13:40

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет фона',
                'verbose_name_plural': 'Цвет фона',
            },
        ),
        migrations.CreateModel(
            name='BackgroundColorSecond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет фона 2',
                'verbose_name_plural': 'Цвет фона 2',
            },
        ),
        migrations.CreateModel(
            name='MainColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Основной цвет',
                'verbose_name_plural': 'Основной цвет',
            },
        ),
        migrations.CreateModel(
            name='SecondaryColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Вторичный цвет',
                'verbose_name_plural': 'Вторичный цвет',
            },
        ),
    ]
