# Generated by Django 4.2 on 2024-04-25 20:32

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalStyles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Глобальные стили',
                'verbose_name_plural': 'Глобальные стили',
            },
        ),
        migrations.CreateModel(
            name='SubheaderText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Цвет')),
                ('font', models.CharField(max_length=15, verbose_name='Шрифт для текста')),
                ('fontWeight', models.CharField(max_length=15, verbose_name='Толщина текста')),
                ('fontWeightMobile', models.CharField(max_length=15, verbose_name='Толщина текста(мобильный)')),
                ('fontSize', models.CharField(max_length=15, verbose_name='Размер текста')),
                ('fontSizeMobile', models.CharField(max_length=15, verbose_name='Размер текста(мобильный)')),
                ('fontColorInverted', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Инвертированный цвет текста')),
                ('global_styles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='styles.globalstyles')),
            ],
            options={
                'verbose_name': 'Подзаголовок',
                'verbose_name_plural': 'Подзаголовок',
            },
        ),
        migrations.CreateModel(
            name='MarginBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margin_top', models.CharField(max_length=20, verbose_name='Отступ сверху')),
                ('margin_bottom', models.CharField(max_length=20, verbose_name='Отступ снизу')),
                ('global_styles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='styles.globalstyles')),
            ],
            options={
                'verbose_name': 'Отступы в блоке',
                'verbose_name_plural': 'Отступы в блоке',
            },
        ),
        migrations.CreateModel(
            name='MainText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Цвет')),
                ('font', models.CharField(max_length=15, verbose_name='Шрифт для текста')),
                ('fontWeight', models.CharField(max_length=15, verbose_name='Толщина текста')),
                ('fontWeightMobile', models.CharField(max_length=15, verbose_name='Толщина текста(мобильный)')),
                ('fontSize', models.CharField(max_length=15, verbose_name='Размер текста')),
                ('fontSizeMobile', models.CharField(max_length=15, verbose_name='Размер текста(мобильный)')),
                ('fontColorInverted', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Инвертированный цвет текста')),
                ('global_styles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='styles.globalstyles')),
            ],
            options={
                'verbose_name': 'Основной текст',
                'verbose_name_plural': 'Основной текст',
            },
        ),
        migrations.CreateModel(
            name='IconSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=20, verbose_name='Высота')),
                ('width', models.CharField(max_length=20, verbose_name='Ширина')),
                ('global_styles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='styles.globalstyles')),
            ],
            options={
                'verbose_name': 'Размер иконок',
                'verbose_name_plural': 'Размер иконок',
            },
        ),
        migrations.CreateModel(
            name='HeaderText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Цвет')),
                ('font', models.CharField(max_length=15, verbose_name='Шрифт для текста')),
                ('fontWeight', models.CharField(max_length=15, verbose_name='Толщина текста')),
                ('fontWeightMobile', models.CharField(max_length=15, verbose_name='Толщина текста(мобильный)')),
                ('fontSize', models.CharField(max_length=15, verbose_name='Размер текста')),
                ('fontSizeMobile', models.CharField(max_length=15, verbose_name='Размер текста(мобильный)')),
                ('fontColorInverted', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Инвертированный цвет текста')),
                ('global_styles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='styles.globalstyles')),
            ],
            options={
                'verbose_name': 'Заголовок',
                'verbose_name_plural': 'Заголовок',
            },
        ),
        migrations.CreateModel(
            name='ExplanationText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Цвет')),
                ('font', models.CharField(max_length=15, verbose_name='Шрифт для текста')),
                ('fontWeight', models.CharField(max_length=15, verbose_name='Толщина текста')),
                ('fontWeightMobile', models.CharField(max_length=15, verbose_name='Толщина текста(мобильный)')),
                ('fontSize', models.CharField(max_length=15, verbose_name='Размер текста')),
                ('fontSizeMobile', models.CharField(max_length=15, verbose_name='Размер текста(мобильный)')),
                ('fontColorInverted', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Инвертированный цвет текста')),
                ('global_styles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='styles.globalstyles')),
            ],
            options={
                'verbose_name': 'Текст пояснний',
                'verbose_name_plural': 'Текст пояснний',
            },
        ),
        migrations.CreateModel(
            name='ColorStyles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Основной цвет')),
                ('secondary_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Вторичный цвет')),
                ('background_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Цвет фона')),
                ('second_background_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Цвет фона 2')),
                ('global_styles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='styles.globalstyles')),
            ],
            options={
                'verbose_name': 'Цвета',
                'verbose_name_plural': 'Цвета',
            },
        ),
    ]
