# Generated by Django 4.2 on 2024-04-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentcustomstyles",
            name="margin_bottom",
            field=models.CharField(max_length=20, null=True, verbose_name="Отступ снизу"),
        ),
        migrations.AlterField(
            model_name="contentcustomstyles",
            name="margin_top",
            field=models.CharField(max_length=20, null=True, verbose_name="Отступ сверху"),
        ),
        migrations.AlterField(
            model_name="covercustomstyles",
            name="margin_bottom",
            field=models.CharField(max_length=20, null=True, verbose_name="Отступ снизу"),
        ),
        migrations.AlterField(
            model_name="covercustomstyles",
            name="margin_top",
            field=models.CharField(max_length=20, null=True, verbose_name="Отступ сверху"),
        ),
        migrations.AlterField(
            model_name="marginblock",
            name="margin_bottom",
            field=models.CharField(max_length=20, null=True, verbose_name="Отступ снизу"),
        ),
        migrations.AlterField(
            model_name="marginblock",
            name="margin_top",
            field=models.CharField(max_length=20, null=True, verbose_name="Отступ сверху"),
        ),
        migrations.AlterField(
            model_name="navbarcustomstyles",
            name="margin_bottom",
            field=models.CharField(max_length=20, null=True, verbose_name="Отступ снизу"),
        ),
        migrations.AlterField(
            model_name="navbarcustomstyles",
            name="margin_top",
            field=models.CharField(max_length=20, null=True, verbose_name="Отступ сверху"),
        ),
    ]
