# Generated by Django 4.2 on 2024-04-24 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalstyles',
            options={'verbose_name': 'Глобальные стили', 'verbose_name_plural': 'Глобальные стили'},
        ),
    ]
