# Generated by Django 4.2.7 on 2024-06-23 19:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PromoCatalogCustomStyles",
        ),
    ]
