# Generated by Django 4.2 on 2024-05-14 10:02

import colorfield.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0007_stagesblock_stage"),
        ("styles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StagesCustomStyles",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("margin_top", models.CharField(blank=True, max_length=20, null=True, verbose_name="Отступ сверху")),
                ("margin_bottom", models.CharField(blank=True, max_length=20, null=True, verbose_name="Отступ снизу")),
                (
                    "background_color",
                    colorfield.fields.ColorField(
                        blank=True,
                        default=None,
                        image_field=None,
                        max_length=25,
                        null=True,
                        samples=None,
                        verbose_name="Цвет фона",
                    ),
                ),
                (
                    "photo_darkness",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Затемнение фото в процентах",
                    ),
                ),
                (
                    "header_size",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="размер заголовка"),
                ),
                (
                    "header_size_mobile",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="размер заголовка (смартфон)"),
                ),
                (
                    "header_thickness",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="толщина заголовка"),
                ),
                (
                    "header_thickness_mobile",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="толщина заголовка (смартфон)"),
                ),
                (
                    "header_color",
                    colorfield.fields.ColorField(
                        blank=True,
                        default=None,
                        image_field=None,
                        max_length=25,
                        null=True,
                        samples=None,
                        verbose_name="Цвет заголовка",
                    ),
                ),
                (
                    "main_text_size",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="размер основного текста"),
                ),
                (
                    "main_text_size_mobile",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="размер основного текста (смартфон)"
                    ),
                ),
                (
                    "main_text_thickness",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="толщина основного текста"),
                ),
                (
                    "main_text_thickness_mobile",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="толщина основного текста (смартфон)"
                    ),
                ),
                (
                    "main_text_color",
                    colorfield.fields.ColorField(
                        blank=True,
                        default=None,
                        image_field=None,
                        max_length=25,
                        null=True,
                        samples=None,
                        verbose_name="Цвет основного текста",
                    ),
                ),
                (
                    "block",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="styles", to="blocks.stagesblock"
                    ),
                ),
            ],
            options={
                "verbose_name": "Кастомные стили",
                "verbose_name_plural": "Кастомные стили",
                "abstract": False,
            },
        ),
    ]
