# Generated by Django 4.2.7 on 2024-06-03 13:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0002_catalogcustomstyles"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CatalogCustomStyles",
        ),
    ]
