# Generated by Django 4.2 on 2024-04-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0002_alter_contentcustomstyles_margin_bottom_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentcustomstyles",
            name="margin_bottom",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Отступ снизу"),
        ),
        migrations.AlterField(
            model_name="contentcustomstyles",
            name="margin_top",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Отступ сверху"),
        ),
        migrations.AlterField(
            model_name="covercustomstyles",
            name="margin_bottom",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Отступ снизу"),
        ),
        migrations.AlterField(
            model_name="covercustomstyles",
            name="margin_top",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Отступ сверху"),
        ),
        migrations.AlterField(
            model_name="marginblock",
            name="margin_bottom",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Отступ снизу"),
        ),
        migrations.AlterField(
            model_name="marginblock",
            name="margin_top",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Отступ сверху"),
        ),
        migrations.AlterField(
            model_name="navbarcustomstyles",
            name="margin_bottom",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Отступ снизу"),
        ),
        migrations.AlterField(
            model_name="navbarcustomstyles",
            name="margin_top",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Отступ сверху"),
        ),
    ]
