# Generated by Django 4.2.7 on 2024-06-23 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0002_mainpagecatalogcustomstyles"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainpagecatalogcustomstyles",
            name="add_annotation",
            field=models.BooleanField(default=True, verbose_name="добавлять аннотацию к карточке"),
        ),
        migrations.AddField(
            model_name="mainpagecatalogcustomstyles",
            name="add_button",
            field=models.BooleanField(default=True, verbose_name="добавлять кнопку к карточке"),
        ),
        migrations.AddField(
            model_name="mainpagecatalogcustomstyles",
            name="darkness_bottom",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                verbose_name="процент затемнения карточки снизу",
            ),
        ),
    ]
