# Generated by Django 4.2 on 2024-05-13 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0006_rename_body_contentblock_text_alter_cover_text"),
        ("styles", "0002_socialcustomstyles_questionscustomstyles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentcustomstyles",
            name="block",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="styles", to="blocks.contentblock"
            ),
        ),
        migrations.AlterField(
            model_name="covercustomstyles",
            name="block",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="styles", to="blocks.cover"
            ),
        ),
        migrations.AlterField(
            model_name="featurescustomstyles",
            name="block",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="styles",
                to="blocks.featuresblock",
            ),
        ),
        migrations.AlterField(
            model_name="navbarcustomstyles",
            name="block",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="styles", to="blocks.navbar"
            ),
        ),
        migrations.AlterField(
            model_name="questionscustomstyles",
            name="block",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="styles",
                to="blocks.questionsblock",
            ),
        ),
        migrations.AlterField(
            model_name="registercustomstyles",
            name="block",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="styles",
                to="blocks.registerblock",
            ),
        ),
        migrations.AlterField(
            model_name="socialcustomstyles",
            name="block",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="styles",
                to="blocks.socialmediablock",
            ),
        ),
    ]
