# Generated by Django 4.2 on 2024-05-12 10:30

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0002_registercustomstyles"),
    ]

    operations = [
        migrations.AddField(
            model_name="registercustomstyles",
            name="button_color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=25, samples=None, verbose_name="цвет кнопки"
            ),
        ),
    ]
