# Generated by Django 4.2 on 2024-05-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0002_featurescustomstyles"),
    ]

    operations = [
        migrations.AddField(
            model_name="featurescustomstyles",
            name="columns",
            field=models.PositiveIntegerField(default=4, verbose_name="Количество колонок"),
        ),
    ]
