# Generated by Django 4.2.7 on 2024-06-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0002_catalogcustomstyles"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogcustomstyles",
            name="columns",
            field=models.PositiveIntegerField(default=4, verbose_name="Количество колонок"),
        ),
    ]
