# Generated by Django 4.2 on 2024-05-14 14:07

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0002_stagescustomstyles"),
    ]

    operations = [
        migrations.AddField(
            model_name="stagescustomstyles",
            name="explanation_text_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
                verbose_name="Цвет текста пояснений",
            ),
        ),
        migrations.AddField(
            model_name="stagescustomstyles",
            name="explanation_text_size",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="размер текста пояснений"),
        ),
        migrations.AddField(
            model_name="stagescustomstyles",
            name="explanation_text_size_mobile",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="размер текста пояснений (смартфон)"
            ),
        ),
        migrations.AddField(
            model_name="stagescustomstyles",
            name="explanation_text_thickness",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="толщина текста пояснений"),
        ),
        migrations.AddField(
            model_name="stagescustomstyles",
            name="explanation_text_thickness_mobile",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="толщина текста пояснений (смартфон)"
            ),
        ),
    ]
