# Generated by Django 4.2 on 2024-08-21 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0002_domain_font_globalstyles_socialnetwork_userfont_and_more"),
        ("styles", "0002_alter_font_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colorstyles",
            name="global_styles",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="settings.globalstyles"
            ),
        ),
        migrations.AlterField(
            model_name="explanationtext",
            name="font",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="settings.font",
                verbose_name="Шрифт для текста",
            ),
        ),
        migrations.AlterField(
            model_name="explanationtext",
            name="global_styles",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="settings.globalstyles"
            ),
        ),
        migrations.AlterField(
            model_name="headertext",
            name="font",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="settings.font",
                verbose_name="Шрифт для текста",
            ),
        ),
        migrations.AlterField(
            model_name="headertext",
            name="global_styles",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="settings.globalstyles"
            ),
        ),
        migrations.AlterField(
            model_name="iconsize",
            name="global_styles",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="settings.globalstyles"
            ),
        ),
        migrations.AlterField(
            model_name="maintext",
            name="font",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="settings.font",
                verbose_name="Шрифт для текста",
            ),
        ),
        migrations.AlterField(
            model_name="maintext",
            name="global_styles",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="settings.globalstyles"
            ),
        ),
        migrations.AlterField(
            model_name="marginblock",
            name="global_styles",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="settings.globalstyles"
            ),
        ),
        migrations.AlterField(
            model_name="subheadertext",
            name="font",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="settings.font",
                verbose_name="Шрифт для текста",
            ),
        ),
        migrations.AlterField(
            model_name="subheadertext",
            name="global_styles",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="settings.globalstyles"
            ),
        ),
        migrations.DeleteModel(
            name="Font",
        ),
        migrations.DeleteModel(
            name="GlobalStyles",
        ),
    ]
