# Generated by Django 4.2 on 2024-05-07 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0006_alter_featuresblock_introductory_text"),
        ("styles", "0003_featurescustomstyles_columns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featurescustomstyles",
            name="block",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="blocks.featuresblock"
            ),
        ),
    ]
