# Generated by Django 4.2.7 on 2024-06-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0003_promocatalogcustomstyles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promocatalogcustomstyles",
            name="columns",
        ),
        migrations.AddField(
            model_name="promocatalogcustomstyles",
            name="swiper_columns",
            field=models.PositiveIntegerField(default=3, verbose_name="Количество колонок в слайдере"),
        ),
    ]
