# Generated by Django 4.2 on 2024-05-13 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0003_alter_contentcustomstyles_block_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colorstyles",
            name="global_styles",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="color_styles",
                to="styles.globalstyles",
            ),
        ),
    ]
