# Generated by Django 4.2 on 2024-05-12 10:42

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0003_registercustomstyles_button_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registercustomstyles",
            name="button_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
                verbose_name="цвет кнопки",
            ),
        ),
    ]
