# Generated by Django 4.2 on 2024-05-13 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0004_alter_colorstyles_global_styles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colorstyles",
            name="global_styles",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="styles.globalstyles"),
        ),
    ]
