# Generated by Django 4.2 on 2024-04-28 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0004_basecolor"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentcustomstyles",
            name="background_color",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="styles.basecolor", verbose_name="Цвет фона"
            ),
        ),
        migrations.AddField(
            model_name="covercustomstyles",
            name="background_color",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="styles.basecolor", verbose_name="Цвет фона"
            ),
        ),
        migrations.AddField(
            model_name="navbarcustomstyles",
            name="background_color",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="styles.basecolor", verbose_name="Цвет фона"
            ),
        ),
    ]
