# Generated by Django 4.2 on 2024-05-07 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blocks", "0006_alter_featuresblock_introductory_text"),
        ("styles", "0004_alter_featurescustomstyles_block"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentcustomstyles",
            name="block",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="blocks.exampleblock"
            ),
        ),
        migrations.AlterField(
            model_name="covercustomstyles",
            name="block",
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to="blocks.cover"),
        ),
        migrations.AlterField(
            model_name="navbarcustomstyles",
            name="block",
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to="blocks.navbar"),
        ),
    ]
