# Generated by Django 4.2 on 2024-05-08 16:06

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0005_alter_contentcustomstyles_block_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="featurescustomstyles",
            name="icon_background_color",
            field=colorfield.fields.ColorField(
                default="#689F38", image_field=None, max_length=25, samples=None, verbose_name="Цвет фона иконок"
            ),
        ),
        migrations.AddField(
            model_name="featurescustomstyles",
            name="icon_color",
            field=colorfield.fields.ColorField(
                default="#689F38", image_field=None, max_length=25, samples=None, verbose_name="Цвет иконок"
            ),
        ),
    ]
