# Generated by Django 4.2 on 2024-05-13 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0005_alter_colorstyles_global_styles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colorstyles",
            name="global_styles",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="styles.globalstyles"
            ),
        ),
        migrations.AlterField(
            model_name="explanationtext",
            name="global_styles",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="styles.globalstyles"
            ),
        ),
        migrations.AlterField(
            model_name="headertext",
            name="global_styles",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="styles.globalstyles"
            ),
        ),
        migrations.AlterField(
            model_name="iconsize",
            name="global_styles",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="styles.globalstyles"
            ),
        ),
        migrations.AlterField(
            model_name="maintext",
            name="global_styles",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="styles.globalstyles"
            ),
        ),
        migrations.AlterField(
            model_name="marginblock",
            name="global_styles",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="styles.globalstyles"
            ),
        ),
        migrations.AlterField(
            model_name="subheadertext",
            name="global_styles",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="styles.globalstyles"
            ),
        ),
    ]
