# Generated by Django 4.2.7 on 2024-07-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0006_remove_mainpagecatalogcustomstyles_add_annotation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="additionalcatalogcustomstyles",
            name="columns",
            field=models.PositiveIntegerField(default=4, verbose_name="Количество колонок"),
        ),
    ]
