# Generated by Django 4.2 on 2024-04-28 11:52

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0006_remove_contentcustomstyles_background_color_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentcustomstyles",
            name="color",
        ),
        migrations.RemoveField(
            model_name="covercustomstyles",
            name="color",
        ),
        migrations.RemoveField(
            model_name="navbarcustomstyles",
            name="color",
        ),
        migrations.AddField(
            model_name="contentcustomstyles",
            name="background_color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=25, samples=None, verbose_name="Цвет фона"
            ),
        ),
        migrations.AddField(
            model_name="covercustomstyles",
            name="background_color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=25, samples=None, verbose_name="Цвет фона"
            ),
        ),
        migrations.AddField(
            model_name="navbarcustomstyles",
            name="background_color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=25, samples=None, verbose_name="Цвет фона"
            ),
        ),
    ]
