# Generated by Django 4.2 on 2024-05-08 16:14

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0006_featurescustomstyles_icon_background_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featurescustomstyles",
            name="icon_background_color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=25, samples=None, verbose_name="Цвет фона иконок"
            ),
        ),
    ]
