# Generated by Django 4.2 on 2024-05-09 09:52

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0007_alter_featurescustomstyles_icon_background_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="featurescustomstyles",
            name="explanation_text_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
                verbose_name="Цвет основного текста",
            ),
        ),
        migrations.AddField(
            model_name="featurescustomstyles",
            name="explanation_text_size",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="размер основного текста"),
        ),
        migrations.AddField(
            model_name="featurescustomstyles",
            name="explanation_text_size_mobile",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="размер основного текста (смартфон)"
            ),
        ),
        migrations.AddField(
            model_name="featurescustomstyles",
            name="explanation_text_thickness",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="толщина основного текста"),
        ),
        migrations.AddField(
            model_name="featurescustomstyles",
            name="explanation_text_thickness_mobile",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="толщина основного текста (смартфон)"
            ),
        ),
        migrations.AddField(
            model_name="featurescustomstyles",
            name="icon_height",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Высота"),
        ),
        migrations.AddField(
            model_name="featurescustomstyles",
            name="icon_width",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Ширина"),
        ),
        migrations.AddField(
            model_name="featurescustomstyles",
            name="sub_header_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
                verbose_name="Цвет заголовка",
            ),
        ),
        migrations.AddField(
            model_name="featurescustomstyles",
            name="sub_header_size",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="размер заголовка"),
        ),
        migrations.AddField(
            model_name="featurescustomstyles",
            name="sub_header_size_mobile",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="размер заголовка (смартфон)"),
        ),
        migrations.AddField(
            model_name="featurescustomstyles",
            name="sub_header_thickness",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="толщина заголовка"),
        ),
        migrations.AddField(
            model_name="featurescustomstyles",
            name="sub_header_thickness_mobile",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="толщина заголовка (смартфон)"),
        ),
    ]
