# Generated by Django 4.2.7 on 2024-07-06 22:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0007_additionalcatalogcustomstyles_columns"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="additionalcatalogcustomstyles",
            name="add_annotation",
        ),
        migrations.RemoveField(
            model_name="additionalcatalogcustomstyles",
            name="add_button",
        ),
    ]
