# Generated by Django 4.2 on 2024-04-28 11:54

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0007_remove_contentcustomstyles_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentcustomstyles",
            name="background_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#FFFFFF",
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
                verbose_name="Цвет фона",
            ),
        ),
        migrations.AlterField(
            model_name="covercustomstyles",
            name="background_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#FFFFFF",
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
                verbose_name="Цвет фона",
            ),
        ),
        migrations.AlterField(
            model_name="navbarcustomstyles",
            name="background_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#FFFFFF",
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
                verbose_name="Цвет фона",
            ),
        ),
    ]
