# Generated by Django 4.2 on 2024-05-09 10:05

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0008_featurescustomstyles_explanation_text_color_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="featurescustomstyles",
            name="sub_header_color",
        ),
        migrations.RemoveField(
            model_name="featurescustomstyles",
            name="sub_header_size",
        ),
        migrations.RemoveField(
            model_name="featurescustomstyles",
            name="sub_header_size_mobile",
        ),
        migrations.RemoveField(
            model_name="featurescustomstyles",
            name="sub_header_thickness",
        ),
        migrations.RemoveField(
            model_name="featurescustomstyles",
            name="sub_header_thickness_mobile",
        ),
        migrations.AddField(
            model_name="featurescustomstyles",
            name="subheader_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
                verbose_name="Цвет подзаголовка",
            ),
        ),
        migrations.AddField(
            model_name="featurescustomstyles",
            name="subheader_size",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="размер подзаголовка"),
        ),
        migrations.AddField(
            model_name="featurescustomstyles",
            name="subheader_size_mobile",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="размер подзаголовка (смартфон)"),
        ),
        migrations.AddField(
            model_name="featurescustomstyles",
            name="subheader_thickness",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="толщина подзаголовка"),
        ),
        migrations.AddField(
            model_name="featurescustomstyles",
            name="subheader_thickness_mobile",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="толщина подзаголовка (смартфон)"
            ),
        ),
        migrations.AlterField(
            model_name="featurescustomstyles",
            name="explanation_text_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
                verbose_name="Цвет текста пояснений",
            ),
        ),
        migrations.AlterField(
            model_name="featurescustomstyles",
            name="explanation_text_size",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="размер текста пояснений"),
        ),
        migrations.AlterField(
            model_name="featurescustomstyles",
            name="explanation_text_size_mobile",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="размер текста пояснений (смартфон)"
            ),
        ),
        migrations.AlterField(
            model_name="featurescustomstyles",
            name="explanation_text_thickness",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="толщина текста пояснений"),
        ),
        migrations.AlterField(
            model_name="featurescustomstyles",
            name="explanation_text_thickness_mobile",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="толщина текста пояснений (смартфон)"
            ),
        ),
        migrations.AlterField(
            model_name="featurescustomstyles",
            name="icon_height",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Высота иконок"),
        ),
        migrations.AlterField(
            model_name="featurescustomstyles",
            name="icon_width",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Ширина иконок"),
        ),
    ]
