# Generated by Django 4.2 on 2024-05-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0009_remove_featurescustomstyles_sub_header_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentcustomstyles",
            name="border_radius",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Радиус скругления картинки"),
        ),
    ]
