# Generated by Django 4.2 on 2024-04-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0009_contentcustomstyles_color_covercustomstyles_color_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentcustomstyles",
            name="color",
        ),
        migrations.RemoveField(
            model_name="covercustomstyles",
            name="color",
        ),
        migrations.RemoveField(
            model_name="navbarcustomstyles",
            name="color",
        ),
        migrations.AddField(
            model_name="contentcustomstyles",
            name="fontSize",
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name="Размер текста"),
        ),
        migrations.AddField(
            model_name="covercustomstyles",
            name="fontSize",
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name="Размер текста"),
        ),
        migrations.AddField(
            model_name="navbarcustomstyles",
            name="fontSize",
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name="Размер текста"),
        ),
        migrations.AlterField(
            model_name="explanationtext",
            name="fontSize",
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name="Размер текста"),
        ),
        migrations.AlterField(
            model_name="headertext",
            name="fontSize",
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name="Размер текста"),
        ),
        migrations.AlterField(
            model_name="maintext",
            name="fontSize",
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name="Размер текста"),
        ),
        migrations.AlterField(
            model_name="subheadertext",
            name="fontSize",
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name="Размер текста"),
        ),
    ]
