# Generated by Django 4.2 on 2024-04-28 13:09

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0010_remove_contentcustomstyles_color_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentcustomstyles",
            name="fontSize",
        ),
        migrations.RemoveField(
            model_name="covercustomstyles",
            name="fontSize",
        ),
        migrations.RemoveField(
            model_name="navbarcustomstyles",
            name="fontSize",
        ),
        migrations.AddField(
            model_name="contentcustomstyles",
            name="header_size_of_text",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="размер заголовка"),
        ),
        migrations.AddField(
            model_name="contentcustomstyles",
            name="header_size_of_text_mobile",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="размер заголовка (смартфон)"),
        ),
        migrations.AddField(
            model_name="contentcustomstyles",
            name="header_text_color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=25, samples=None, verbose_name="Цвет заголовка"
            ),
        ),
        migrations.AddField(
            model_name="contentcustomstyles",
            name="header_thickness_of_text",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="толшина заголовка"),
        ),
        migrations.AddField(
            model_name="contentcustomstyles",
            name="header_thickness_of_text_mobile",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="толщина заголовка (смартфон)"),
        ),
        migrations.AddField(
            model_name="contentcustomstyles",
            name="main_text_size_of_text",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="размер основного текста"),
        ),
        migrations.AddField(
            model_name="contentcustomstyles",
            name="main_text_size_of_text_mobile",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="размер основного текста (смартфон)"
            ),
        ),
        migrations.AddField(
            model_name="contentcustomstyles",
            name="main_text_text_color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=25, samples=None, verbose_name="Цвет заголовка"
            ),
        ),
        migrations.AddField(
            model_name="contentcustomstyles",
            name="main_text_thickness_of_text",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="толщтна основного текста"),
        ),
        migrations.AddField(
            model_name="contentcustomstyles",
            name="main_text_thickness_of_text_mobile",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="толщтна основного текста (смартфон)"
            ),
        ),
        migrations.AddField(
            model_name="covercustomstyles",
            name="header_size_of_text",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="размер заголовка"),
        ),
        migrations.AddField(
            model_name="covercustomstyles",
            name="header_size_of_text_mobile",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="размер заголовка (смартфон)"),
        ),
        migrations.AddField(
            model_name="covercustomstyles",
            name="header_text_color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=25, samples=None, verbose_name="Цвет заголовка"
            ),
        ),
        migrations.AddField(
            model_name="covercustomstyles",
            name="header_thickness_of_text",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="толшина заголовка"),
        ),
        migrations.AddField(
            model_name="covercustomstyles",
            name="header_thickness_of_text_mobile",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="толщина заголовка (смартфон)"),
        ),
        migrations.AddField(
            model_name="covercustomstyles",
            name="main_text_size_of_text",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="размер основного текста"),
        ),
        migrations.AddField(
            model_name="covercustomstyles",
            name="main_text_size_of_text_mobile",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="размер основного текста (смартфон)"
            ),
        ),
        migrations.AddField(
            model_name="covercustomstyles",
            name="main_text_text_color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=25, samples=None, verbose_name="Цвет заголовка"
            ),
        ),
        migrations.AddField(
            model_name="covercustomstyles",
            name="main_text_thickness_of_text",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="толщтна основного текста"),
        ),
        migrations.AddField(
            model_name="covercustomstyles",
            name="main_text_thickness_of_text_mobile",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="толщтна основного текста (смартфон)"
            ),
        ),
        migrations.AddField(
            model_name="navbarcustomstyles",
            name="header_size_of_text",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="размер заголовка"),
        ),
        migrations.AddField(
            model_name="navbarcustomstyles",
            name="header_size_of_text_mobile",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="размер заголовка (смартфон)"),
        ),
        migrations.AddField(
            model_name="navbarcustomstyles",
            name="header_text_color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=25, samples=None, verbose_name="Цвет заголовка"
            ),
        ),
        migrations.AddField(
            model_name="navbarcustomstyles",
            name="header_thickness_of_text",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="толшина заголовка"),
        ),
        migrations.AddField(
            model_name="navbarcustomstyles",
            name="header_thickness_of_text_mobile",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="толщина заголовка (смартфон)"),
        ),
        migrations.AddField(
            model_name="navbarcustomstyles",
            name="main_text_size_of_text",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="размер основного текста"),
        ),
        migrations.AddField(
            model_name="navbarcustomstyles",
            name="main_text_size_of_text_mobile",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="размер основного текста (смартфон)"
            ),
        ),
        migrations.AddField(
            model_name="navbarcustomstyles",
            name="main_text_text_color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=25, samples=None, verbose_name="Цвет заголовка"
            ),
        ),
        migrations.AddField(
            model_name="navbarcustomstyles",
            name="main_text_thickness_of_text",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="толщтна основного текста"),
        ),
        migrations.AddField(
            model_name="navbarcustomstyles",
            name="main_text_thickness_of_text_mobile",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="толщтна основного текста (смартфон)"
            ),
        ),
    ]
