# Generated by Django 4.2 on 2024-04-28 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0012_rename_header_size_of_text_contentcustomstyles_header_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentcustomstyles",
            name="photo_darkness",
            field=models.PositiveIntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)],
                verbose_name="Затемнение фото в процентах",
            ),
        ),
        migrations.AddField(
            model_name="covercustomstyles",
            name="photo_darkness",
            field=models.PositiveIntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)],
                verbose_name="Затемнение фото в процентах",
            ),
        ),
        migrations.AddField(
            model_name="navbarcustomstyles",
            name="photo_darkness",
            field=models.PositiveIntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)],
                verbose_name="Затемнение фото в процентах",
            ),
        ),
    ]
