# Generated by Django 5.0 on 2024-09-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TryLoginToAdminPanel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("client_ip", models.CharField(max_length=15, verbose_name="ip с которого был запрос")),
                ("login", models.CharField(max_length=100, verbose_name="логин")),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Попытка входа в админку",
                "verbose_name_plural": "Попытки входа в админку",
            },
        ),
    ]
