# Generated by Django 5.0 on 2024-09-19 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_statistics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TryLoginToFakeAdminPanel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("client_ip", models.CharField(max_length=15, verbose_name="ip с которого был запрос")),
                ("login", models.CharField(max_length=100, verbose_name="логин")),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Попытка входа в фейковую админку",
                "verbose_name_plural": "Попытки входа в фейковую админку",
            },
        ),
    ]
