# Generated by Django 5.0 on 2024-09-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_statistics", "0002_trylogintofakeadminpanel"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ip", models.CharField(max_length=15)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("banks_count", models.PositiveIntegerField(default=0)),
                ("pages_count", models.PositiveIntegerField(default=0)),
                ("popups_count", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
