# Generated by Django 5.0 on 2024-09-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_statistics", "0003_useractivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="useractivity",
            name="unique_key",
            field=models.CharField(max_length=1000, null=True, unique=True),
        ),
    ]
