# Generated by Django 5.0 on 2024-09-25 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_statistics", "0005_useractivity_auth"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoToThePage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.CharField(max_length=300)),
                (
                    "session",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="site_statistics.useractivity"),
                ),
            ],
        ),
    ]
