# Generated by Django 5.0 on 2024-09-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_statistics", "0006_gotothepage"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("adress", models.CharField(max_length=300, verbose_name="страница")),
                ("text", models.CharField(max_length=200, verbose_name="")),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Событие",
                "verbose_name_plural": "События",
                "ordering": ["-id"],
            },
        ),
        migrations.AlterModelOptions(
            name="gotothepage",
            options={"ordering": ["-id"], "verbose_name": "страница", "verbose_name_plural": "Переходы по страницам"},
        ),
    ]
