# Generated by Django 5.0 on 2024-09-25 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_statistics", "0007_useraction_alter_gotothepage_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraction",
            name="session",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="site_statistics.useractivity"
            ),
        ),
    ]
