# Generated by Django 5.0 on 2024-09-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_statistics", "0008_useraction_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivity",
            name="unique_key",
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
    ]
