# Generated by Django 5.0 on 2024-09-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_statistics", "0009_alter_useractivity_unique_key"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="useractivity",
            options={"verbose_name": "Посетители", "verbose_name_plural": "Посетители"},
        ),
        migrations.AddField(
            model_name="useraction",
            name="site",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
