# Generated by Django 5.0 on 2024-09-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_statistics", "0010_alter_useractivity_options_useraction_site"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraction",
            name="site",
        ),
        migrations.AddField(
            model_name="useractivity",
            name="site",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
