# Generated by Django 5.0 on 2024-09-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_statistics", "0011_remove_useraction_site_useractivity_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="useractivity",
            name="device",
            field=models.BooleanField(default=False),
        ),
    ]
