# Generated by Django 5.0 on 2024-09-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_statistics", "0013_useractivity_user_alter_useractivity_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="useractivity",
            name="profile_actions_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Действия в лк"),
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="banks_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Банки"),
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="pages_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Страницы"),
        ),
    ]
