# Generated by Django 5.0 on 2024-09-27 02:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("site_statistics", "0014_useractivity_profile_actions_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useractivity",
            name="popups_count",
        ),
    ]
