# Generated by Django 5.0 on 2024-09-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_statistics", "0015_remove_useractivity_popups_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="useractivity",
            name="utm_source",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="site",
            field=models.CharField(max_length=50, null=True, verbose_name="Сайт"),
        ),
    ]
