# Generated by Django 5.0 on 2024-09-27 23:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("site_statistics", "0018_sessionfilters_sessionmodel_auth_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sessionaction",
            options={"ordering": ["-time"], "verbose_name": "Событие", "verbose_name_plural": "События"},
        ),
        migrations.AlterModelOptions(
            name="useraction",
            options={"ordering": ["-time"], "verbose_name": "Событие", "verbose_name_plural": "События"},
        ),
        migrations.RemoveField(
            model_name="sessionaction",
            name="text",
        ),
    ]
