# Generated by Django 5.0 on 2024-09-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_statistics", "0021_sessionmodel_source_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionmodel",
            name="headers",
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="useractivity",
            name="headers",
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
