# Generated by Django 5.0 on 2024-10-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_statistics", "0026_rename_disable_ports_sessionfilters_ports_penalty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionfilters",
            name="capcha_success",
            field=models.SmallIntegerField(default=0, verbose_name="Успешная капча"),
        ),
        migrations.AddField(
            model_name="sessionfiltersheader",
            name="penalty",
            field=models.SmallIntegerField(default=0),
        ),
    ]
