# Generated by Django 5.0 on 2024-10-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_statistics", "0027_sessionfilters_capcha_success_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionfilters",
            name="disable_urls_penalty",
            field=models.SmallIntegerField(default=0, verbose_name="Несуществующий адрес"),
        ),
        migrations.AlterField(
            model_name="sessionfilters",
            name="ip_penalty",
            field=models.SmallIntegerField(default=0, verbose_name="Запрос к IP"),
        ),
        migrations.AlterField(
            model_name="sessionfilters",
            name="ports_penalty",
            field=models.SmallIntegerField(default=0, verbose_name="Запретить обращение к нетипичным портам"),
        ),
    ]
