# Generated by Django 5.0 on 2024-10-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_statistics", "0029_rename_bun_rate_sessionmodel_ban_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionfilters",
            name="not_found_page_penalty",
            field=models.SmallIntegerField(default=0, verbose_name="Несуществующий адрес"),
        ),
        migrations.AlterField(
            model_name="sessionfilters",
            name="ban_limit",
            field=models.SmallIntegerField(default=10000, verbose_name="Порог бана"),
        ),
        migrations.AlterField(
            model_name="sessionfilters",
            name="capcha_limit",
            field=models.SmallIntegerField(default=10000, verbose_name="Порог капчи"),
        ),
        migrations.AlterField(
            model_name="sessionfilters",
            name="disable_urls_penalty",
            field=models.SmallIntegerField(default=0, verbose_name="Запрещенный адрес"),
        ),
        migrations.AlterField(
            model_name="sessionfilters",
            name="ports_penalty",
            field=models.SmallIntegerField(default=0, verbose_name="Запрос к порту"),
        ),
        migrations.AlterField(
            model_name="sessionmodel",
            name="ban_rate",
            field=models.SmallIntegerField(default=0, verbose_name="Штраф"),
        ),
    ]
