# Generated by Django 5.0 on 2024-10-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_statistics", "0031_rename_not_found_page_penalty_sessionfilters_page_not_found_penalty"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionfiltersheader",
            name="content",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
