# Generated by Django 5.0 on 2024-10-14 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_statistics", "0032_sessionfiltersheader_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionfiltersheader",
            name="contain",
            field=models.CharField(
                choices=[
                    ("Присутствует", "Присутствует"),
                    ("Отсутствует", "Отсутствует"),
                    ("Содержит", "Содержит"),
                    ("Не содержит", "Не содержит"),
                    ("Совпадает", "Совпадает"),
                    ("Не совпадает", "Не совпадает"),
                ],
                max_length=50,
                verbose_name="содержит",
            ),
        ),
        migrations.AlterField(
            model_name="sessionfiltersheader",
            name="content",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="строка"),
        ),
        migrations.AlterField(
            model_name="sessionfiltersheader",
            name="penalty",
            field=models.SmallIntegerField(default=0, verbose_name="штраф"),
        ),
        migrations.AlterField(
            model_name="sessionfiltersheader",
            name="session_filters",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="headers", to="site_statistics.sessionfilters"
            ),
        ),
        migrations.CreateModel(
            name="PenaltyLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.CharField(max_length=500)),
                (
                    "session",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="site_statistics.sessionmodel"),
                ),
            ],
        ),
    ]
