# Generated by Django 5.0 on 2024-10-15 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_statistics", "0034_websearcher"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebSearcherAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("adress", models.CharField(max_length=300, verbose_name="страница")),
                ("time", models.DateTimeField()),
                (
                    "searcher",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="site_statistics.websearcher"),
                ),
            ],
            options={
                "verbose_name": "Событие",
                "verbose_name_plural": "События",
                "ordering": ["-time"],
            },
        ),
    ]
