# Generated by Django 5.0 on 2024-10-15 01:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_statistics", "0035_websearcheraction"),
    ]

    operations = [
        migrations.AddField(
            model_name="websearcher",
            name="headers",
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
