# Generated by Django 5.0 on 2024-10-15 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_statistics", "0036_websearcher_headers"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionfilters",
            name="disable_urls_sites",
            field=models.TextField(null=True, verbose_name="Запрос содержит(сайты)"),
        ),
        migrations.AlterField(
            model_name="sessionfilters",
            name="disable_urls",
            field=models.TextField(verbose_name="Запрос содержит(все)"),
        ),
        migrations.AlterField(
            model_name="sessionfilters",
            name="searchers",
            field=models.CharField(max_length=500, null=True, verbose_name="Поисковики"),
        ),
        migrations.AlterField(
            model_name="websearcheraction",
            name="searcher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="actions", to="site_statistics.websearcher"
            ),
        ),
    ]
