# Generated by Django 5.0 on 2024-10-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_statistics", "0037_sessionfilters_disable_urls_sites_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionfiltersheader",
            name="content",
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name="строка"),
        ),
    ]
