# Generated by Django 5.0 on 2024-10-15 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_statistics", "0038_alter_sessionfiltersheader_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="useractivity",
            name="session",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="site_statistics.sessionmodel"
            ),
        ),
    ]
