# Generated by Django 5.0 on 2024-10-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_statistics", "0039_useractivity_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionfilters",
            name="no_cookie",
            field=models.SmallIntegerField(default=0, verbose_name="Нет cookies"),
        ),
    ]
