# Generated by Django 5.0 on 2024-10-15 14:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("site_statistics", "0040_sessionfilters_no_cookie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sessionmodel",
            name="auth",
        ),
        migrations.RemoveField(
            model_name="sessionmodel",
            name="banks_count",
        ),
        migrations.RemoveField(
            model_name="sessionmodel",
            name="hacking_reason",
        ),
        migrations.RemoveField(
            model_name="sessionmodel",
            name="profile_actions_count",
        ),
        migrations.RemoveField(
            model_name="sessionmodel",
            name="user",
        ),
        migrations.RemoveField(
            model_name="useractivity",
            name="hacking",
        ),
        migrations.RemoveField(
            model_name="useractivity",
            name="hacking_reason",
        ),
    ]
