# Generated by Django 5.0 on 2024-10-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_statistics", "0041_remove_sessionmodel_auth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionfilters",
            name="disallowed_host",
            field=models.SmallIntegerField(default=0, verbose_name="Несуществующий домен"),
        ),
    ]
