# Generated by Django 5.0 on 2024-10-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_statistics", "0043_sessionfilters_hide_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionmodel",
            name="show_capcha",
            field=models.BooleanField(default=False),
        ),
    ]
