# Generated by Django 5.0 on 2024-10-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_statistics", "0044_sessionmodel_show_capcha"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionmodel",
            name="checked_single_page",
            field=models.BooleanField(default=False),
        ),
    ]
