# Generated by Django 5.0 on 2024-10-21 01:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("site_statistics", "0045_sessionmodel_checked_single_page"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sessionmodel",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="useractivity",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="websearcher",
            name="end_time",
        ),
    ]
