# Generated by Django 5.0 on 2024-10-23 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_statistics", "0046_remove_sessionmodel_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraction",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="actions", to="site_statistics.useractivity"
            ),
        ),
    ]
