# Generated by Django 5.0 on 2024-12-03 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_statistics", "0047_alter_useraction_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivity",
            name="session",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="site_statistics.sessionmodel"),
        ),
    ]
