# Generated by Django 5.0 on 2024-12-05 16:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("site_statistics", "0048_alter_useractivity_session"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useractivity",
            name="utm_source",
        ),
    ]
