# Generated by Django 4.2 on 2024-07-10 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=300, verbose_name="название")),
                ("message", models.CharField(max_length=600, verbose_name="сообщение")),
                (
                    "status",
                    models.CharField(
                        choices=[("warning", "предупреждение"), ("error", "ошибка"), ("info", "информационное")],
                        max_length=100,
                        null=True,
                        verbose_name="статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "уведомление",
                "verbose_name_plural": "уведомления",
            },
        ),
        migrations.CreateModel(
            name="Trigger",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="триггер")),
            ],
            options={
                "verbose_name": "триггер",
                "verbose_name_plural": "триггеры",
            },
        ),
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_created", models.DateTimeField(auto_now_add=True, verbose_name="дата создания")),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notifications.notification",
                        verbose_name="уведомление",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "пользовательское уведомление",
                "verbose_name_plural": "пользовательские уведомления",
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="trigger",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="notifications.trigger",
                verbose_name="триггер",
            ),
        ),
    ]
