# Generated by Django 4.2 on 2024-07-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usernotification",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name="дата создания"),
        ),
    ]
